### ISSUE TITLE
Java 1.7 Linux sound crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#130]
```
An unexpected error occurred.

You should consider submitting an error report via the project issue list:

http://code.google.com/p/open-ig/issues/list

Please include the following diagnostic information followed by the error 
stacktrace(s):

   Java version: 1.7.0_147-icedtea
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Linux, i386, 3.0.0-13-generic
   Game version: 0.93.480
   Command line: [-memonce]
   Available memory: 317 MB
   Maximum memory: 742 MB
   Parallelism: 4
   Startup language: hu
----

Exception in thread "PulseAudio Eventloop Thread" 
java.lang.IllegalStateException: drain failed
    at org.classpath.icedtea.pulseaudio.EventLoop.native_iterate(Native Method)
    at org.classpath.icedtea.pulseaudio.EventLoop.run(EventLoop.java:141)
    at java.lang.Thread.run(Thread.java:722)


A játékot ugyan tudom folytatni, de immár hang nélkül! :(
```

Original issue reported on code.google.com by `Jozsef.T...@gmail.com` on 25 Dec 2011 at 12:02

**Comment by GoogleCodeExporter** [comment]
```
Valószínűleg az OpenJDK és az Oracle JDK akad össze, már amennyire utána 
tudtam nézni. Mindenesetre próbáld meg a legfrissebb SVN-verzióval.
```

Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 1:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 1:46
- Changed title: **Java 1.7 Linux sound crash**

**Comment by GoogleCodeExporter** [comment]
```
A régi OpenJDK összeakadna az 1.7-es Oracle JDK -val?
```

Original comment by `Jozsef.T...@gmail.com` on 25 Dec 2011 at 2:01

**Comment by GoogleCodeExporter** [comment]
```
Igen, gyakori probléma.
```

Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 2:47

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 27 Dec 2011 at 12:33
- Added labels: **Sound**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 30 Dec 2011 at 5:38
- Changed state: **Fixed**
