### ISSUE TITLE
Some ships are frozen during spacewar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#133]
```
I have noticed that if my fleet becomes bigger, 2 or 3 fighters are always 
frozen during the battle. I can select these ships but they do not react on any 
orders. If I'm attacking a planet without alien ships I'm unable to loose or 
retreat.

BTW is groundwar working? I've been to place tanks and start battle, but unable 
to move any tanks (maybe I don't know something because I never played original 
IG)  
```

Original issue reported on code.google.com by `troex@fury.scancode.ru` on 25 Dec 2011 at 5:13

**Comment by GoogleCodeExporter** [comment]
```
Could you send me a save just before the attack. Its under 
save/default/save-???.xml
Do not send the savex-???.xml file!

The ground war should work: did you unpause the game?
```

Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 5:54

**Comment by GoogleCodeExporter** [comment]
```
Sure, try to attack "Magellan 2" with "Foflotta". Usually what I start spacewar 
I got some error dialog but I usually dismiss it, do need info from it?

I'll check groundwar once again...
```

Original comment by `troex@fury.scancode.ru` on 25 Dec 2011 at 6:13

Attachments:
- [save-2011-12-25-20-00-59-807.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-133/comment-2/save-2011-12-25-20-00-59-807.xml)

**Comment by GoogleCodeExporter** [comment]
```
Please send the error dialog contents as well.
```

Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 7:20
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 7:21
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
This is the error I get when starting spacewar with frozen ships (always 
fighters)

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Linux, i386, 3.0.0-14-generic
   Game version: 0.93.481
   Command line: [-memonce]
   Available memory: 227 MB
   Maximum memory: 682 MB
   Parallelism: 2
   Startup language: hu
----
    <entry key='spacewar.ship_status_none'></entry>
java.lang.AssertionError
    at hu.openig.core.Labels.get(Labels.java:57)
    at hu.openig.screen.ScreenBase.get(ScreenBase.java:149)
    at hu.openig.screen.items.SpacewarScreen$ShipStatusPanel.displayNone(SpacewarScreen.java:2210)
    at hu.openig.screen.items.SpacewarScreen.displaySelectedShipInfo(SpacewarScreen.java:915)
    at hu.openig.screen.items.SpacewarScreen.onEnter(SpacewarScreen.java:967)
    at hu.openig.GameWindow.display(GameWindow.java:649)
    at hu.openig.GameWindow.displayPrimary(GameWindow.java:681)
    at hu.openig.GameWindow.startBattle(GameWindow.java:1591)
    at hu.openig.screen.CommonResources.startBattle(CommonResources.java:772)
    at hu.openig.mechanics.Simulator.compute(Simulator.java:123)
    at hu.openig.screen.CommonResources.simulation(CommonResources.java:509)
    at hu.openig.screen.CommonResources$16.invoke(CommonResources.java:488)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:636)
    at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:192)
    at javax.swing.Timer.fireActionPerformed(Timer.java:312)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:244)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:705)
    at java.awt.EventQueue.access$000(EventQueue.java:101)
    at java.awt.EventQueue$3.run(EventQueue.java:666)
    at java.awt.EventQueue$3.run(EventQueue.java:664)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:675)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
    <entry key='message.yesterday_trade_income'></entry>
java.lang.AssertionError
    at hu.openig.core.Labels.get(Labels.java:57)
    at hu.openig.screen.ScreenBase.get(ScreenBase.java:149)
    at hu.openig.screen.items.StatusbarScreen$MovingNotification.getTextWidth(StatusbarScreen.java:373)
    at hu.openig.screen.items.StatusbarScreen$MovingNotification.draw(StatusbarScreen.java:301)
    at hu.openig.ui.UIContainer.draw(UIContainer.java:71)
    at hu.openig.screen.items.StatusbarScreen.draw(StatusbarScreen.java:243)
    at hu.openig.GameWindow$ScreenRenderer.paint(GameWindow.java:178)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5221)
    at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:295)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1206)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5169)
    at javax.swing.JComponent.paintImmediately(JComponent.java:4980)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:770)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:728)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:677)
    at javax.swing.RepaintManager.access$700(RepaintManager.java:59)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1621)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:705)
    at java.awt.EventQueue.access$000(EventQueue.java:101)
    at java.awt.EventQueue$3.run(EventQueue.java:666)
    at java.awt.EventQueue$3.run(EventQueue.java:664)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:675)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

Original comment by `troex@fury.scancode.ru` on 25 Dec 2011 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
And about the groundwar... I still cannot move my tanks, and I don't see any 
controls, M and A shortcuts also do not work. I'm attaching screenshot, maybe 
I'm missing some interface controls?
```

Original comment by `troex@fury.scancode.ru` on 25 Dec 2011 at 8:09

Attachments:
- [open-ig-frozen-groundwar.png](https://storage.googleapis.com/google-code-attachments/open-ig/issue-133/comment-6/open-ig-frozen-groundwar.png)

**Comment by GoogleCodeExporter** [comment]
```
I found only way to escape groundwar is to press backspace... I don't know what 
it really does, but I'm back to starmap and can continue to play
```

Original comment by `troex@fury.scancode.ru` on 25 Dec 2011 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
There is still a debate about how to control units and the screen pan. 
Currently, you can move ground and space units by holding SHIFT and right 
clicking at a destination. Attacking is done by CTRL + Right click.
```

Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 8:25

**Comment by GoogleCodeExporter** [comment]
```
The Backspace key is intentional. I use it during testing to quickly back out 
from battle.
```

Original comment by `akarn...@gmail.com` on 25 Dec 2011 at 8:36

**Comment by GoogleCodeExporter** [comment]
```
Thanks, looks like now with .490 my ships are not frozen anymore and also now I 
understand howto control ground units.

How even after the spacewar or groundwar victory I get error which pauses the 
game and what ever I try to unpause it throws the error again and doesn't allow 
to continue. Backspace helps to get back.

Attaching errors.
```

Original comment by `troex@fury.scancode.ru` on 26 Dec 2011 at 7:13

Attachments:
- [after-groundwar-victory-error.txt](https://storage.googleapis.com/google-code-attachments/open-ig/issue-133/comment-10/after-groundwar-victory-error.txt)

**Comment by GoogleCodeExporter** [comment]
```
Update to version 0.93.491
```

Original comment by `akarn...@gmail.com` on 26 Dec 2011 at 8:56

**Comment by GoogleCodeExporter** [comment]
```
Updated, spacewar works fine, but somehow enemy turrets do not attack me 
anymore.

After groundwar finish I still got this error, and have to use backspace to 
finish groundwar.

P.S.: Maybe this bugs from that I played game for some days and updated from 
480 to 491. I'll start new game after NY and check once again. Thanks!


Error after groundwar finished:


An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Linux, i386, 3.0.0-14-generic
   Game version: 0.93.491
   Command line: [-memonce]
   Available memory: 228 MB
   Maximum memory: 682 MB
   Parallelism: 2
   Startup language: hu
----
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at hu.openig.screen.items.PlanetScreen.damageArea(PlanetScreen.java:3963)
    at hu.openig.screen.items.PlanetScreen.updateRocket(PlanetScreen.java:4514)
    at hu.openig.screen.items.PlanetScreen.doGroundWarSimulation(PlanetScreen.java:3562)
    at hu.openig.screen.items.PlanetScreen$25.invoke(PlanetScreen.java:2923)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:637)
    at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:193)
    at javax.swing.Timer.fireActionPerformed(Timer.java:312)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:244)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:705)
    at java.awt.EventQueue.access$000(EventQueue.java:101)
    at java.awt.EventQueue$3.run(EventQueue.java:666)
    at java.awt.EventQueue$3.run(EventQueue.java:664)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:675)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
    at hu.openig.screen.items.PlanetScreen.concludeBattle(PlanetScreen.java:3654)
    at hu.openig.screen.items.PlanetScreen.doGroundWarSimulation(PlanetScreen.java:3576)
    at hu.openig.screen.items.PlanetScreen$25.invoke(PlanetScreen.java:2923)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:637)
    at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:193)
    at javax.swing.Timer.fireActionPerformed(Timer.java:312)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:244)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:705)
    at java.awt.EventQueue.access$000(EventQueue.java:101)
    at java.awt.EventQueue$3.run(EventQueue.java:666)
    at java.awt.EventQueue$3.run(EventQueue.java:664)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:675)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

Original comment by `troex@fury.scancode.ru` on 27 Dec 2011 at 10:32

**Comment by GoogleCodeExporter** [comment]
```
Can you send me a new save for the case where you only need to fight the ground 
battle?
```

Original comment by `akarn...@gmail.com` on 27 Dec 2011 at 11:09

**Comment by GoogleCodeExporter** [comment]
```
Never mind, I found the problem. Check for updates.
```

Original comment by `akarn...@gmail.com` on 27 Dec 2011 at 12:24
- Changed state: **Fixed**
