### ISSUE TITLE
Start the game and getting error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#15]
```
Game version:
0.92b

Operating System: (e.g., Windows 7 x86, Windows XP 64-bit)
Xp sp3 pro

Java runtime version: (run java -version)
6

Installed using the Launcher? (yes, no)
Im using a .bat etc
I have DL all the zip, put in the folder, even unzip all the stuff and try

What steps will reproduce the problem?
1.star the campaing
2.
3.


What is the expected output? What do you see instead?

this error :

Exception in thread "Movie Video" java.lang.NullPointerException
    at hu.openig.screen.VideoRenderer.run(VideoRenderer.java:77)
Exception in thread "Start Game Loading" java.lang.AssertionError: Missing 
resource: en campaign/main/diplomacy
    at hu.openig.core.ResourceLocator.getXML(ResourceLocator.java:485)
    at hu.openig.model.World.load(World.java:143)
    at hu.openig.screen.items.SingleplayerScreen$6.run(SingleplayerScreen.java:227)


Please provide any additional information below.

```

Original issue reported on code.google.com by `chromaph...@gmail.com` on 19 Jul 2011 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
Please upgrade the game to 0.92 via the launcher.

You should also remove the extracted directories.
```

Original comment by `akarn...@gmail.com` on 19 Jul 2011 at 9:17
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi

I have try your launcher, seems i have missed some stuff, the launcher download 
new package. When I start the game now, the intro video (a man is walking in 
his ship/station) but just after i got new issue :-(

Exception in thread "Start Game Loading" java.lang.NumberFormatException: For 
input string: "+150"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at hu.openig.utils.XElement.getInt(XElement.java:122)
    at hu.openig.model.Diplomacy.parse(Diplomacy.java:99)
    at hu.openig.model.World.load(World.java:153)
    at hu.openig.screen.items.SingleplayerScreen$6.run(SingleplayerScreen.java:227)

Thanks
```

Original comment by `chromaph...@gmail.com` on 19 Jul 2011 at 9:29

**Comment by GoogleCodeExporter** [comment]
```
Yeah, Java 6. Somehow it doesn't like the plus sign before integers. For me in 
Java 7 works perfectly.

I fixed it but with the same version number, therefore, you need to convince 
the launcher to re-download the changed file by deleting 

launcher-confix.xml

but keep everything else. If you start the Launcher and click Install, it will 
detect the existing files and only re-download what has changed.
```

Original comment by `akarn...@gmail.com` on 19 Jul 2011 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
Hi, Yes i did all the stuff deleting then relauncher the upgrader but...

I cant find java 7, I have seen that there is a sdk for java 7 but if i want 
java for computer they give me just the java 6 version 26 on the official site 
:(

thanks
```

Original comment by `chromaph...@gmail.com` on 19 Jul 2011 at 10:48

**Comment by GoogleCodeExporter** [comment]
```
here is the link for java 7
http://www.oracle.com/technetwork/java/javase/downloads/java-se-jre-7-download-4
32155.html
```

Original comment by `Jozsef.T...@gmail.com` on 14 Aug 2011 at 8:19
