### ISSUE TITLE
főépület rombolás - hiba

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#156]
```
Van amikor kevés egységem marad földi csatáknál, és olyankor amennyi 
épületet csak tudok lerombolok (köztük a főépületet is), és erre 
hibaüzenettel reagál az AI (és nem építi újra a főépületet):

Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException
    at java.util.ArrayList$Itr.next(Unknown Source)
    at java.util.Collections.max(Unknown Source)
    at hu.openig.model.PlanetSurface$PlacementHelper.nearestAdjust(PlanetSurface.java:690)
    at hu.openig.model.PlanetSurface$PlacementHelper.findLocation(PlanetSurface.java:642)
    at hu.openig.model.PlanetSurface$PlacementHelper.findLocation(PlanetSurface.java:601)
    at hu.openig.mechanics.DefaultAIControls.actionPlaceBuilding(DefaultAIControls.java:207)
    at hu.openig.mechanics.ColonyPlanner$15.invoke(ColonyPlanner.java:633)
    at hu.openig.mechanics.AI.apply(AI.java:99)
    at hu.openig.mechanics.AIMixed.apply(AIMixed.java:70)
    at hu.openig.screen.CommonResources$19.run(CommonResources.java:549)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original issue reported on code.google.com by `Jozsef.T...@gmail.com` on 30 Dec 2011 at 9:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `Jozsef.T...@gmail.com` on 30 Dec 2011 at 9:51
- Added labels: **Milestone-0.93.600**
- Removed labels: **Milestone-0.93.500**

**Comment by GoogleCodeExporter** [comment]
```
Épp az épület elhelyezést próbálom finomítani. Próbáld most.
```

Original comment by `akarn...@gmail.com` on 30 Dec 2011 at 10:25

**Comment by GoogleCodeExporter** [comment]
```
Nincs hibaüzenet, de nem is építi újra.
```

Original comment by `Jozsef.T...@gmail.com` on 30 Dec 2011 at 10:31

**Comment by GoogleCodeExporter** [comment]
```
Rombold le a center 10 en a főépületet, és nézd meg a konzolban az AI 
gondját.
```

Original comment by `Jozsef.T...@gmail.com` on 30 Dec 2011 at 10:48

Attachments:
- [save-2011-12-30-23-44-16-654.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-156/comment-4/save-2011-12-30-23-44-16-654.xml)

**Comment by GoogleCodeExporter** [comment]
```
az utolsó frissítés jót tett, mostmár meg tudja építeni, eddig nem 
talált neki helyet, azért nem épített azon a bolygón.

```

Original comment by `Jozsef.T...@gmail.com` on 30 Dec 2011 at 10:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `Jozsef.T...@gmail.com` on 1 Jan 2012 at 11:38
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 11 Jan 2012 at 7:56
- Changed state: **Fixed**
