### ISSUE TITLE
Megállt az AI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#167]
```
Teljesen leállt, kb 40 perce nem csinál semmit, a konzolban is csak 4 vonal.
(SVN 0.93.520)

```

Original issue reported on code.google.com by `Jozsef.T...@gmail.com` on 5 Jan 2012 at 7:02

Attachments:
- [save-2012-01-05-19-56-01-350.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-167/comment-0/save-2012-01-05-19-56-01-350.xml)

**Comment by GoogleCodeExporter** [comment]
```
Betöltöttem a mentést,(valamiért bennt is ragat a jawaw.exe a folyamatok 
között) és a következő a hibaüzenet:
java.lang.AssertionError: Warning: Persol 2, MilitaryDevCenter
    at hu.openig.mechanics.ResearchPlanner.buildOneLabIf(ResearchPlanner.java:500)
    at hu.openig.mechanics.ResearchPlanner.buildOneLabFor(ResearchPlanner.java:466)
    at hu.openig.mechanics.ResearchPlanner.planReconstruction(ResearchPlanner.java:349)
    at hu.openig.mechanics.ResearchPlanner.plan(ResearchPlanner.java:132)
    at hu.openig.mechanics.Planner.run(Planner.java:182)
    at hu.openig.mechanics.AI.manage(AI.java:397)
    at hu.openig.screen.CommonResources.runAI(CommonResources.java:548)
    at hu.openig.screen.CommonResources$18.run(CommonResources.java:527)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

A persol 2-őn egy kikapcsolt mechanikai fejlesztő kp. van.
```

Original comment by `Jozsef.T...@gmail.com` on 5 Jan 2012 at 7:08

**Comment by GoogleCodeExporter** [comment]
```
Úgy nézem, hogy nem számolja bele a kikapcsolt fejlesztő kp.t, és 
megpróbál mégegyet építeni, de nem lehet.

java.lang.AssertionError: Warning: Center 12, MilitaryDevCenter
    at hu.openig.mechanics.ResearchPlanner.buildOneLabIf(ResearchPlanner.java:500)
    at hu.openig.mechanics.ResearchPlanner.buildOneLabFor(ResearchPlanner.java:466)
    at hu.openig.mechanics.ResearchPlanner.planReconstruction(ResearchPlanner.java:349)
    at hu.openig.mechanics.ResearchPlanner.plan(ResearchPlanner.java:132)
    at hu.openig.mechanics.Planner.run(Planner.java:182)
    at hu.openig.mechanics.AI.manage(AI.java:397)
    at hu.openig.mechanics.AIMixed.manage(AIMixed.java:64)
    at hu.openig.screen.CommonResources.runAI(CommonResources.java:548)
    at hu.openig.screen.CommonResources$18.run(CommonResources.java:527)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Az AI "fagyást" még nem tudtam megismételni.
```

Original comment by `Jozsef.T...@gmail.com` on 5 Jan 2012 at 7:46

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 11 Jan 2012 at 1:43
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 11 Jan 2012 at 8:01
- Changed state: **Fixed**
