### ISSUE TITLE
Missions: Verify Mission 7 Task 1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#235]
```
Verify the first task of Mission 7

- happens one week after the completion of Mission 6
- random trader gets attacked
- checkStartTask method contains the attacker configuration

What is needed:

- balance, based on how much the player can do within a week in terms of 
firepower
- what is the message from the trader?
- any custom battle finish image?
```

Original issue reported on code.google.com by `akarn...@gmail.com` on 20 Jan 2012 at 7:26

**Comment by GoogleCodeExporter** [comment]
```
Task 2 depends on Mission 12 Task 1 completion, which is not there yet and you 
can't trigger it by regular means.
```

Original comment by `akarn...@gmail.com` on 20 Jan 2012 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
- what is the message from the trader? labels.xml
- any custom battle finish image? mission_1_8d.png
```

Original comment by `Jozsef.T...@gmail.com` on 20 Jan 2012 at 6:55
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Oké, a szövegeket megtaláltam a 2, 3, 6 és 7-hez.
```

Original comment by `akarn...@gmail.com` on 20 Jan 2012 at 7:09

**Comment by GoogleCodeExporter** [comment]
```
Hibaüzenet:

<entry key='Garthog.fleet_name'></entry>
java.lang.AssertionError
    at hu.openig.core.Labels.get(Labels.java:57)
    at hu.openig.scripting.missions.Mission.label(Mission.java:145)
    at hu.openig.scripting.missions.Mission7.checkStartTask(Mission7.java:119)
    at hu.openig.scripting.missions.Mission7.onTime(Mission7.java:60)
    at hu.openig.scripting.MainCampaignScripting.onTime(MainCampaignScripting.java:659)
    at hu.openig.mechanics.Simulator.compute(Simulator.java:121)
    at hu.openig.screen.CommonResources.simulation(CommonResources.java:571)
    at hu.openig.screen.CommonResources$16.invoke(CommonResources.java:497)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:677)
    at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:201)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

Ha jól értem hiányzik egy bejegyzés a labels.xml-ből
```

Original comment by `Jozsef.T...@gmail.com` on 20 Jan 2012 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
Ja. Most már benne van.
```

Original comment by `akarn...@gmail.com` on 20 Jan 2012 at 10:19

**Comment by GoogleCodeExporter** [comment]
```
Új hibaüzenet kezdéskor:

java.lang.NullPointerException
    at hu.openig.model.Fleet.addInventory(Fleet.java:266)
    at hu.openig.scripting.missions.Mission7.checkStartTask(Mission7.java:124)
    at hu.openig.scripting.missions.Mission7.onTime(Mission7.java:60)
    at hu.openig.scripting.MainCampaignScripting.onTime(MainCampaignScripting.java:659)
    at hu.openig.mechanics.Simulator.compute(Simulator.java:121)
    at hu.openig.screen.CommonResources.simulation(CommonResources.java:571)
    at hu.openig.screen.CommonResources$16.invoke(CommonResources.java:497)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:677)
    at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:201)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original comment by `Jozsef.T...@gmail.com` on 21 Jan 2012 at 11:29

**Comment by GoogleCodeExporter** [comment]
```
El volt írva a vadász neve. Javítva.
```

Original comment by `akarn...@gmail.com` on 21 Jan 2012 at 11:38

**Comment by GoogleCodeExporter** [comment]
```
Érdekes, észrevettem, hogy le van sérülve pár hajóm, elloholtam az 
Achillesig, majd amikor visszaindultam, elment a flotta, de azért megtámadtam 
a kereskedőt, és űrharcnál viszont ott voltak a Garthogok.
```

Original comment by `Jozsef.T...@gmail.com` on 24 Jan 2012 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
Az AI valamiért mégis átvette felette az irányítást. Átírom, hogy ne is 
lássa az ilyen flottákat.
```

Original comment by `akarn...@gmail.com` on 24 Jan 2012 at 8:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 2 Mar 2012 at 9:32
- Changed state: **Done**
