### ISSUE TITLE
Űrbázis v1&mi-felügyelet bolygón=0 tűzerő

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#251]
```
Ha az Mi suereli fel a bolygómat űrbázissal 0 tűzereje lesz az 
űrbázisoknak!

```

Original issue reported on code.google.com by `Jozsef.T...@gmail.com` on 22 Jan 2012 at 11:15

**Comment by GoogleCodeExporter** [comment]
```
Itt egy kép is róla.
```

Original comment by `Jozsef.T...@gmail.com` on 22 Jan 2012 at 11:15

Attachments:
- [hiba.png](https://storage.googleapis.com/google-code-attachments/open-ig/issue-251/comment-1/hiba.png)

**Comment by GoogleCodeExporter** [comment]
```
És a harc után ez a hibaüzenet:

java.lang.NullPointerException
    at hu.openig.screen.items.BattlefinishScreen.lossCount(BattlefinishScreen.java:350)
    at hu.openig.screen.items.BattlefinishScreen.draw(BattlefinishScreen.java:190)
    at hu.openig.GameWindow$ScreenRenderer.paint(GameWindow.java:185)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
    at javax.swing.RepaintManager.paint(Unknown Source)
    at javax.swing.JComponent._paintImmediately(Unknown Source)
    at javax.swing.JComponent.paintImmediately(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.access$700(Unknown Source)
    at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original comment by `Jozsef.T...@gmail.com` on 22 Jan 2012 at 11:19

**Comment by GoogleCodeExporter** [comment]
```
Mindkettő javítva. Amúgy ha újra betöltesz egy állást, megjavul az 
űrállomás felszerelése.
```

Original comment by `akarn...@gmail.com` on 22 Jan 2012 at 11:24
- Changed state: **SVN**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 29 Jan 2012 at 4:09
- Changed state: **Fixed**
