### ISSUE TITLE
Subtitle for achilles_check video

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#276]
```
Example: data/hu/messages/san_sterling_check.sub

00:01.200-00:03.600 Csak azért hívom, hogy megtudjam, minden rendben van-e.
00:04.000-00:08.400 Köszönöm, hogy aggódik értünk, de ha problémánk 
támad, rögtön szólunk.


Required:

data/hu/messages/achilles_check.sub
data/en/messages/achilles_check.sub
```

Original issue reported on code.google.com by `akarn...@gmail.com` on 3 Feb 2012 at 2:20

**Comment by GoogleCodeExporter** [comment]
Original comment by `Jozsef.T...@gmail.com` on 5 Feb 2012 at 12:20
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Teljesen mindegy, hogy hogy írom be a szöveget/időzítést, mindig ez a 
hibaüzenet:
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For 
input string: "﻿0"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at hu.openig.core.SubtitleManager.loadSub(SubtitleManager.java:70)
    at hu.openig.core.SubtitleManager.<init>(SubtitleManager.java:57)
    at hu.openig.tools.VideoPlayer.playVideo(VideoPlayer.java:700)
    at hu.openig.tools.VideoPlayer.doPlay(VideoPlayer.java:628)
    at hu.openig.tools.VideoPlayer.doMouseClicked(VideoPlayer.java:682)
    at hu.openig.tools.VideoPlayer$3.mouseClicked(VideoPlayer.java:411)
    at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

Original comment by `Jozsef.T...@gmail.com` on 5 Feb 2012 at 11:49

**Comment by GoogleCodeExporter** [comment]
```
A fájlt másold be légyszi.
```

Original comment by `akarn...@gmail.com` on 5 Feb 2012 at 12:33

**Comment by GoogleCodeExporter** [comment]
```
Tessék.
```

Original comment by `Jozsef.T...@gmail.com` on 5 Feb 2012 at 2:04

Attachments:
- [achilles_check.sub](https://storage.googleapis.com/google-code-attachments/open-ig/issue-276/comment-4/achilles_check.sub)

**Comment by GoogleCodeExporter** [comment]
```
Vedd ki a szóközt az első sor elejéről
2012.02.05. 15:05, <open-ig@googlecode.com> ezt írta:
```

Original comment by `akarn...@gmail.com` on 5 Feb 2012 at 2:07

**Comment by GoogleCodeExporter** [comment]
```
Nekem ott nem mutat szóközt, vagy nem egyre gondolunk.
```

Original comment by `Jozsef.T...@gmail.com` on 5 Feb 2012 at 5:05

**Comment by GoogleCodeExporter** [comment]
```
A szövegszerkesztőd valószínüleg betett egy un. BOM karaktert. Úgy ments,
hogy ne legyen benne.
2012.02.05. 18:06, <open-ig@googlecode.com> ezt írta:
```

Original comment by `akarn...@gmail.com` on 5 Feb 2012 at 5:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `Jozsef.T...@gmail.com` on 5 Feb 2012 at 7:45
- Changed state: **SVN**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 10 Feb 2012 at 1:07
- Changed state: **Fixed**
