### ISSUE TITLE
Crash around Mission 7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#340]
```
Error approx. 10 seonds after Alt + Tab:


An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows 7, amd64, 6.1
   Game version: 0.94.357
   Command line: [-memonce, -en]
   Available memory: 378 MB
   Maximum memory: 1820 MB
   Parallelism: 4
   Startup language: hu
----
java.lang.NullPointerException
    at hu.openig.scripting.missions.Mission7.spacewarStartTraderVsPirate(Mission7.java:233)
    at hu.openig.scripting.missions.Mission7.onSpacewarStart(Mission7.java:331)
    at hu.openig.scripting.MainCampaignScripting.onSpacewarStart(MainCampaignScripting.java:938)
    at hu.openig.screen.items.SpacewarScreen.initiateBattle(SpacewarScreen.java:1371)
    at hu.openig.GameWindow.startBattle(GameWindow.java:1982)
    at hu.openig.screen.CommonResources.startBattle(CommonResources.java:849)
    at hu.openig.mechanics.Simulator.compute(Simulator.java:113)
    at hu.openig.screen.CommonResources.simulation(CommonResources.java:585)
    at hu.openig.screen.CommonResources$17.invoke(CommonResources.java:507)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:696)
    at hu.openig.screen.CommonResources$2.actionPerformed(CommonResources.java:211)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original issue reported on code.google.com by `norbert....@gmail.com` on 15 Apr 2012 at 6:33

**Comment by GoogleCodeExporter** [comment]
```
Startup language: hu

???

No way :D
```

Original comment by `norbert....@gmail.com` on 15 Apr 2012 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
Please send me your save just before the attack.
```

Original comment by `akarn...@gmail.com` on 15 Apr 2012 at 8:44

**Comment by GoogleCodeExporter** [comment]
```
Should be this one:

https://rapidshare.com/files/1587461315/Attack.rar
```

Original comment by `norbert....@gmail.com` on 16 Apr 2012 at 5:54

**Comment by GoogleCodeExporter** [comment]
```
I don't see any problems with this save.
```

Original comment by `akarn...@gmail.com` on 16 Apr 2012 at 8:35

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I didn't make myself clear. I didn't have a particular problem. I played 
the game, Alt+tabbed, browsed the internet and then suddenly I had that error 
log. I switched back to the game and kept on playing. But still, that error log 
WAS there ;)
```

Original comment by `norbert....@gmail.com` on 16 Apr 2012 at 9:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 21 Apr 2012 at 8:59
- Changed title: **Crash around Mission 7**
- Changed state: **Accepted**
- Added labels: **Missions**, **Milestone-0.94.400**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 3 May 2012 at 8:32

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 7 May 2012 at 12:19
- Changed state: **SVN**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 13 May 2012 at 4:08
- Changed state: **Fixed**
