### ISSUE TITLE
Error starting german version

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#360]
```
OIG set to german, Windowed game


An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows 7, amd64, 6.1
   Game version: 0.94.360
   Command line: [-memonce, -de]
   Available memory: 355 MB
   Maximum memory: 1820 MB
   Parallelism: 4
   Startup language: hu
----
Exception in thread "Movie Video" java.lang.NullPointerException
    at hu.openig.screen.VideoRenderer.run(VideoRenderer.java:129)

```

Original issue reported on code.google.com by `norbert....@gmail.com` on 21 Apr 2012 at 11:26

**Comment by GoogleCodeExporter** [comment]
```
You tried to start a new game? Was there any video playing before this error?
```

Original comment by `akarn...@gmail.com` on 21 Apr 2012 at 11:52

**Comment by GoogleCodeExporter** [comment]
```
Yes I tried a new game. The introduction video (colonel is giving me my new 
post) is playing fine. After that the error log appears (both in windowed mode 
and in fullscreen) and I can play jus fine...
```

Original comment by `norbert....@gmail.com` on 21 Apr 2012 at 11:59

**Comment by GoogleCodeExporter** [comment]
```
but it also happens by loading a saved game
```

Original comment by `norbert....@gmail.com` on 21 Apr 2012 at 12:01

**Comment by GoogleCodeExporter** [comment]
```
Try with the new 361.
```

Original comment by `akarn...@gmail.com` on 21 Apr 2012 at 12:05

**Comment by GoogleCodeExporter** [comment]
```
Still the same:

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows 7, amd64, 6.1
   Game version: 0.94.361
   Command line: [-memonce, -de]
   Available memory: 135 MB
   Maximum memory: 1820 MB
   Parallelism: 4
   Startup language: hu
----
Exception in thread "Movie Video" java.lang.NullPointerException
    at hu.openig.screen.VideoRenderer.run(VideoRenderer.java:129)

```

Original comment by `norbert....@gmail.com` on 21 Apr 2012 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
Okay, I see now. There are missing animations for the bridge. Please run a 
check for new version and verify install to get the missing file.
```

Original comment by `akarn...@gmail.com` on 21 Apr 2012 at 12:18
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
And Btw, could you send me these files from the german ANIM directory:

*HID*.ANI
```

Original comment by `akarn...@gmail.com` on 21 Apr 2012 at 12:20
- Added labels: **Milestone-0.94.400**

**Comment by GoogleCodeExporter** [comment]
```
Error is gone. 

Your requested files:

https://rapidshare.com/files/3335958892/IG.rar
```

Original comment by `norbert....@gmail.com` on 21 Apr 2012 at 12:28

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 29 Apr 2012 at 9:06
- Changed state: **SVN**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 30 Apr 2012 at 7:00
- Changed state: **Fixed**
