### ISSUE TITLE
First Conquest

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#429]
```
Game version: 0.94.373


Operating System: (e.g., Windows 7 x86, Windows XP 64-bit) Vista


Java runtime version: (run java -version) latest 6


Installed using the Launcher? (yes, no) y


Game language (en, hu): en


What steps will reproduce the problem?
1. Commander: Attack Garthog 1 with Main Fleet once Garthog Explorer moves off.
2. Destroy the 3 defending forts to win.
3. Profit! Wait... Whats this huge error message!
Game still continues once conquest summary is closed.


What is the expected output? What do you see instead?

On defeat of the forts the success summary comes up but so does a never ending 
error message. I havent included it due to its never ending nature, but I hope 
you can reproduce it from my save, I will try to get a copy/paste of some of it 
if need be, just ask :-)

Please provide any additional information below.

Save file included.
```

Original issue reported on code.google.com by `Phil6...@googlemail.com` on 4 May 2012 at 12:07

Attachments:
- [save-2012-05-04-12-51-58-322.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-429/comment-0/save-2012-05-04-12-51-58-322.xml)

**Comment by GoogleCodeExporter** [comment]
```
The error is probably the same thing repeated multiple times, it would be very 
helpful. Oh, and next time, please zip your save.
```

Original comment by `akarn...@gmail.com` on 4 May 2012 at 12:10

**Comment by GoogleCodeExporter** [comment]
```
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.6.0_31
   Java vendor: Sun Microsystems Inc. (http://java.sun.com/)
   Java class version: 50.0
   Operating system: Windows Vista, x86, 6.0
   Game version: 0.94.373
   Command line: [-memonce, -en]
   Available memory: 224 MB
   Maximum memory: 742 MB
   Parallelism: 2
   Startup language: hu
----
java.lang.NullPointerException
    at hu.openig.screen.items.BattlefinishScreen.enemyStatus(BattlefinishScreen.java:301)
    at hu.openig.screen.items.BattlefinishScreen.draw(BattlefinishScreen.java:259)
    at hu.openig.GameWindow$ScreenRenderer.paint(GameWindow.java:187)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
    at javax.swing.RepaintManager.paint(Unknown Source)
    at javax.swing.JComponent._paintImmediately(Unknown Source)
    at javax.swing.JComponent.paintImmediately(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.access$700(Unknown Source)
    at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.NullPointerException
    at hu.openig.screen.items.BattlefinishScreen.enemyStatus(BattlefinishScreen.java:301)
    at hu.openig.screen.items.BattlefinishScreen.draw(BattlefinishScreen.java:259)
    at hu.openig.GameWindow$ScreenRenderer.paint(GameWindow.java:197)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JLayeredPane.paint(Unknown Source)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
    at javax.swing.RepaintManager.paint(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
    at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
    at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
    at java.awt.Container.paint(Unknown Source)
    at java.awt.Window.paint(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.access$700(Unknown Source)
    at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.NullPointerException


And several more pages in the first few seconds :-)
Again more available if you want it :-)
```

Original comment by `Phil6...@googlemail.com` on 4 May 2012 at 4:13

**Comment by GoogleCodeExporter** [comment]
```
Thanks. Update to 0.94.374
```

Original comment by `akarn...@gmail.com` on 4 May 2012 at 4:41
- Changed state: **SVN**
- Added labels: **Milestone-0.94.400**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 13 May 2012 at 4:30
- Changed state: **Fixed**
