### ISSUE TITLE
First quarantine mission

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#458]
```
Something is very wrong with the traders behaviour in the first quarantine 
mission (Level2):

They don't turn away after succesfully persuading them by space chat.

That way, traders go on trying to reach their destination. If you catch them 
again, there are no space chat option any longer. Instead the old log is being 
shown.

I'm also under the impression that "Govenor Mc Allision" is being mentioned far 
to often :)

Addionally an error log appears:

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows 7, amd64, 6.1
   Game version: 0.94.405
   Command line: [-memonce, -en]
   Available memory: 393 MB
   Maximum memory: 1820 MB
   Parallelism: 4
   Startup language: hu
----
java.lang.ArithmeticException: / by zero
    at hu.openig.mechanics.AITrader.spaceBattleInit(AITrader.java:465)
    at hu.openig.screen.items.SpacewarScreen.initiateBattle(SpacewarScreen.java:1392)
    at hu.openig.GameWindow.startBattle(GameWindow.java:1997)
    at hu.openig.screen.CommonResources.startBattle(CommonResources.java:868)
    at hu.openig.mechanics.Simulator.compute(Simulator.java:121)
    at hu.openig.screen.CommonResources.simulation(CommonResources.java:604)
    at hu.openig.screen.CommonResources$18.invoke(CommonResources.java:526)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:715)
    at hu.openig.screen.CommonResources$2.actionPerformed(CommonResources.java:216)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original issue reported on code.google.com by `norbert....@gmail.com` on 21 May 2012 at 11:26

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 21 May 2012 at 11:58
- Changed state: **SVN**
- Added labels: **Milestone-0.95**

**Comment by GoogleCodeExporter** [comment]
```
Don't want to open a new issue:

http://img440.imageshack.us/img440/9125/errorlogs.jpg

which results in:

http://img534.imageshack.us/img534/3105/java2012052118133375.jpg
```

Original comment by `norbert....@gmail.com` on 21 May 2012 at 4:16

**Comment by GoogleCodeExporter** [comment]
```
And another one:

A second infected planet still quits the game.
```

Original comment by `norbert....@gmail.com` on 21 May 2012 at 7:51

**Comment by GoogleCodeExporter** [comment]
```
well, there IS our cure (you remeber our conversation, do you?):

http://img836.imageshack.us/img836/2139/java2012052121485092.jpg

I thought you weren't able to find it.

The problem is: OpenIG handles this trader like any other, which means it gets 
infected and infects other planets...

So, first of all: Where did you find it? And second: What do we do with him. 
Until now I wasn't able to find him in DOS IG again.
```

Original comment by `norbert....@gmail.com` on 21 May 2012 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
Maybe I just had bad luck or the random generator regarding space chat is kind 
of strange.

Yesterday I told you about the omnipresent Govenor Mc Allison. It seems you 
fixed it because now he doesn't exist anymore. My new friend is Trader MH4 :)
```

Original comment by `norbert....@gmail.com` on 21 May 2012 at 11:04

**Comment by GoogleCodeExporter** [comment]
```
Now it's the fugitives. This has to change :D
```

Original comment by `norbert....@gmail.com` on 22 May 2012 at 11:19

**Comment by GoogleCodeExporter** [comment]
```
To be clear, they don't turn around if you chat them, but they do if you just 
shoot them outright?
```

Original comment by `akarn...@gmail.com` on 22 May 2012 at 11:21

**Comment by GoogleCodeExporter** [comment]
```
ähm....they DO return now..either by space chat or by force.. So no problem 
there. You fixed it.


Right now I'm talking about the responses I am getting.
```

Original comment by `norbert....@gmail.com` on 22 May 2012 at 11:22

**Comment by GoogleCodeExporter** [comment]
```
I resolved the original crash.

You might have met with the same trader multiple times. It seems the original 
had 8 numbered trader fixed. I'm not sure if they were replenished in case of 
destruction. I might later switch to this case for levels 1-3.

For the 2 infection limit, can you repeat the case and make sure you don't get 
more than 1 additional infection due simultaneous arrival of traders?


```

Original comment by `akarn...@gmail.com` on 22 May 2012 at 11:36

**Comment by GoogleCodeExporter** [comment]
```
"You might have met with the same trader multiple times."

How is that possible? I sent them back to the infected planet. They should stay 
there, shouldn't they?
```

Original comment by `norbert....@gmail.com` on 22 May 2012 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
They stay there for about 60 step (which is 6 hours on normal), regular traders 
come and go in 10 steps. I'll need to fix it to proper ingame time and probably 
increase the stay length.
```

Original comment by `akarn...@gmail.com` on 22 May 2012 at 11:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 22 May 2012 at 2:45
- Changed state: **Fixed**
