### ISSUE TITLE
Error after attacking trader

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#473]
```
Error after attacking trader

java.lang.NullPointerException
    at hu.openig.mechanics.AITrader.landFleets(AITrader.java:295)
    at hu.openig.mechanics.AITrader.apply(AITrader.java:171)
    at hu.openig.screen.CommonResources$21.run(CommonResources.java:585)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original issue reported on code.google.com by `norbert....@gmail.com` on 22 May 2012 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
Sorry:

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows 7, amd64, 6.1
   Game version: 0.94.410
   Command line: [-memonce, -en]
   Available memory: 487 MB
   Maximum memory: 1820 MB
   Parallelism: 4
   Startup language: hu
----
java.lang.NullPointerException
    at hu.openig.mechanics.AITrader.landFleets(AITrader.java:295)
    at hu.openig.mechanics.AITrader.apply(AITrader.java:171)
    at hu.openig.screen.CommonResources$21.run(CommonResources.java:585)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

Original comment by `norbert....@gmail.com` on 22 May 2012 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
I haven't done a separate release, run a verify install to repair
```

Original comment by `akarn...@gmail.com` on 22 May 2012 at 3:18
- Changed state: **SVN**
- Added labels: **Milestone-0.95**

**Comment by GoogleCodeExporter** [comment]
```
Did a verification and the error is gone. That was fast :)
```

Original comment by `norbert....@gmail.com` on 22 May 2012 at 11:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 29 May 2012 at 12:45
- Changed state: **Fixed**
