### ISSUE TITLE
A few diplomacy related issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#486]
```
Most recent version.

-One of the races requested credits from me, but they didn't say the exact 
amount, instead '%s' was displayed.

-Continous false messages from the Garthogs through the diplomacy window, but 
they were already defeated years ago, and nothing happens as a result.

-Some of the races surrendered to me, yet when I ask them to give up, they'll 
get mad instead and I lose even more dilomacy points.

-'Alliance against the dargslans' option is available when talking to the 
darglans, resulting in an error.

-The 'form alliance' and 'manage diplomatic relations' options are not working, 
but I suppose those aren't fully functional yet.

```

Original issue reported on code.google.com by `sosetala...@gmail.com` on 26 May 2012 at 1:28

**Comment by GoogleCodeExporter** [comment]
```
Hi and thanks for looking into the Diplomacy.

I forgot about the request money, but I'm not sure wether there was an 
accept/decline in the original? Currenlty, it is soo random that if aliens 
request money, they may slill reject a regular money offer.

Defeated empires should not issue diplomatic offers, I'll fix that. If they 
surrender on their own, the conversation will be terminated.

What was the error with the dargslan-dargslan option?

The alliance option should work, you must see a list of commonly known empires. 
Manage diplomatic relations should work as well. How were they not working?
```

Original comment by `akarn...@gmail.com` on 26 May 2012 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
<entry key='diplomacy.Dargslan.DARGSLAN.58'></entry>
    <entry key='diplomacy.Dargslan.DARGSLAN.NO.63'></entry>

This is for the darglsan one.

http://noob.hu/2012/05/26/alliance.jpg
http://noob.hu/2012/05/26/relations.jpg

Forming an alliance is not an option initially, when I press 'Cancel' and try 
forming one again, there'll be 2 'Cancel' buttons and so on 3,4,5 etc. Pressing 
either of those and any of the choices in the relations panel will result in 
the following error:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at hu.openig.screen.items.DiplomacyScreen.doEnemies(DiplomacyScreen.java:1277)
    at hu.openig.screen.items.DiplomacyScreen$8.invoke(DiplomacyScreen.java:218)
    at hu.openig.screen.items.DiplomacyScreen$8.invoke(DiplomacyScreen.java:1)
    at hu.openig.screen.OptionList.mouse(OptionList.java:124)
    at hu.openig.ui.UIContainer.mouse(UIContainer.java:113)
    at hu.openig.screen.ScreenBase.mouse(ScreenBase.java:105)
    at hu.openig.screen.items.DiplomacyScreen.mouse(DiplomacyScreen.java:425)
    at hu.openig.GameWindow$MouseActions.invoke(GameWindow.java:1450)
    at hu.openig.GameWindow$MouseActions.mouseReleased(GameWindow.java:1484)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$2.run(Unknown Source)
    at java.awt.EventQueue$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original comment by `sosetala...@gmail.com` on 26 May 2012 at 2:20

**Comment by GoogleCodeExporter** [comment]
```
Try with 0.94.421.
```

Original comment by `akarn...@gmail.com` on 26 May 2012 at 2:54
- Changed state: **SVN**
- Added labels: **Milestone-0.95**

**Comment by GoogleCodeExporter** [comment]
```
The 'relations' tab seems to be working now. But forming an alliance is still 
broken.

http://noob.hu/2012/05/26/alliancesp1.jpg

This happens when I click to it.

http://noob.hu/2012/05/26/alliancesp2.jpg

And this happens when I click to either of the choices.

```

Original comment by `sosetala...@gmail.com` on 26 May 2012 at 3:17

**Comment by GoogleCodeExporter** [comment]
```
Thanks. Excelent example when one bug hides another...

I fixed this but haven't incremented the version number. Just run a verify 
install.
```

Original comment by `akarn...@gmail.com` on 26 May 2012 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
It seems to be working now, but the message refers to the hu.openig..package 
instead of the actual race name, when it says "alliance against player0526 
something"
```

Original comment by `sosetala...@gmail.com` on 26 May 2012 at 7:43

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 29 May 2012 at 12:55
- Changed state: **Fixed**
