### ISSUE TITLE
Smuggler Mission not completing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#492]
```
Game version:
0.94.421

Operating System: (e.g., Windows 7 x86, Windows XP 64-bit)
Windows 7 64bit

Java runtime version: (run java -version)
Java 7 Update 4

Installed using the Launcher? (yes, no)
Yes

Game language (en, hu, de):
en

What steps will reproduce the problem?
1. Promotion to captain
2. Destroy the smuggler
3.


What is the expected output? What do you see instead?
Mission should complete in order to carry on with the game

Please provide any additional information below.
Running AI on planets, 30mins/step
```

Original issue reported on code.google.com by `Gawie.Sc...@ggtech.co.za` on 28 May 2012 at 12:04

**Comment by GoogleCodeExporter** [comment]
```
The mission failure stays longer on than usual. Could you upload a save about 
the situation after the trader was destroyed?
```

Original comment by `akarn...@gmail.com` on 28 May 2012 at 12:41

**Comment by GoogleCodeExporter** [comment]
```
First thing. When I attack it, and it turns around, it doesn't return to 
anywhere... It stays at the attacked site.

After I destroyed it, nothing happens.

Find both before destroy and after saves attached.
```

Original comment by `Gawie.Sc...@ggtech.co.za` on 28 May 2012 at 12:46

Attachments:
- [Before.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-492/comment-2/Before.zip)
- [After.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-492/comment-2/After.zip)

**Comment by GoogleCodeExporter** [comment]
```
This is quite the funny one...

I loaded from the "Level 2 Start" save... Then saved as soon as I got the 
smuggler alert.

When I attack it, and let it turn around near naxos, it just stays there...
When I attack it, and let it turn around near San Sterling, it returned to 
Achilles.

Although, in the middle between naxos and san sterling, it left...

I get this message every time though...

java.lang.AssertionError: Fleet 49 has no previous planet to return to!
    at hu.openig.mechanics.AITrader.returnToPreviousPlanet(AITrader.java:474)
    at hu.openig.mechanics.AITrader.spaceBattleDone(AITrader.java:461)
    at hu.openig.screen.items.SpacewarScreen.concludeBattle(SpacewarScreen.java:4096)
    at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3604)
    at hu.openig.screen.items.SpacewarScreen$8.invoke(SpacewarScreen.java:2909)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:718)
    at hu.openig.screen.CommonResources$2.actionPerformed(CommonResources.java:216)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original comment by `Gawie.Sc...@ggtech.co.za` on 28 May 2012 at 1:09

Attachments:
- [Before Attack.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-492/comment-3/Before Attack.zip)
- [Level 2 start.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-492/comment-3/Level 2 start.zip)

**Comment by GoogleCodeExporter** [comment]
```
Yes, it looks very messed up. Could you please retry with 0.94.423 from Level 2 
start.
I suggest you do keep a save before the smuggler mission pops up. 
```

Original comment by `akarn...@gmail.com` on 28 May 2012 at 1:37
- Changed state: **SVN**
- Added labels: **Milestone-0.95**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 29 May 2012 at 12:58
- Changed state: **Fixed**
