### ISSUE TITLE
Garthog diplomacy

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#567]
```
Calling the Garthog on the Diplomacy screen causes an error.

I can understand why as calling the Garthog in DOS IG was not an option, so 
this has to be done from scratch.


An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.6.0_31
   Java vendor: Sun Microsystems Inc. (http://java.sun.com/)
   Java class version: 50.0
   Operating system: Windows XP, x86, 5.1
   Game version: 0.95.006
   Command line: [-memonce, -hu]
   Available memory: 241 MB
   Maximum memory: 742 MB
   Parallelism: 1
   Startup language: hu
A crash save has been created, please attach it in the issue report (zipped).
----
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at hu.openig.screen.items.DiplomacyScreen.doOption(DiplomacyScreen.java:1118)
    at hu.openig.screen.items.DiplomacyScreen$5.invoke(DiplomacyScreen.java:196)
    at hu.openig.screen.items.DiplomacyScreen$5.invoke(DiplomacyScreen.java:1)
    at hu.openig.screen.OptionList.mouse(OptionList.java:124)
    at hu.openig.ui.UIContainer.mouse(UIContainer.java:113)
    at hu.openig.screen.ScreenBase.mouse(ScreenBase.java:109)
    at hu.openig.screen.items.DiplomacyScreen.mouse(DiplomacyScreen.java:434)
    at hu.openig.GameWindow$MouseActions.invoke(GameWindow.java:1494)
    at hu.openig.GameWindow$MouseActions.mouseReleased(GameWindow.java:1528)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.awt.EventQueue$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$2.run(Unknown Source)
    at java.awt.EventQueue$2.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original issue reported on code.google.com by `gharr...@gmail.com` on 19 Jun 2012 at 4:08

Attachments:
- [save-2012-06-19-18-03-26-187.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-567/comment-0/save-2012-06-19-18-03-26-187.zip)

**Comment by GoogleCodeExporter** [comment]
```
With diligence, anyone could do this. Would you be up to the task? Just fill in 
the structure below:

    <player id="Garthog">
        <negotiate type="DIPLOMATIC_RELATIONS">
            <approach type="AGGRESSIVE">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.1</approach>
            <approach type="AGGRESSIVE">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.2</approach>
            <approach type="AGGRESSIVE">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.3</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.4</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.5</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.6</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.HUMBLE.7</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.HUMBLE.8</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.HUMBLE.9</approach>
            <response type="AGGRESSIVE" mode="YES" change="150">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.10</response>
            <response type="AGGRESSIVE" mode="YES" change="120">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.11</response>
            <response type="AGGRESSIVE" mode="YES" change="100">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.12</response>
            <response type="AGGRESSIVE" mode="MAYBE" change="-80">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.13</response>
            <response type="AGGRESSIVE" mode="MAYBE" change="-70">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.14</response>
            <response type="AGGRESSIVE" mode="MAYBE" change="-50">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.15</response>
            <response type="AGGRESSIVE" mode="NO" notalk="true" change="-150">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.16</response>
            <response type="AGGRESSIVE" mode="NO" notalk="true" change="-250">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.17</response>
            <response type="AGGRESSIVE" mode="NO" notalk="true" change="-270">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.18</response>
            <response type="NEUTRAL" mode="YES" change="160">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.YES.19</response>
            <response type="NEUTRAL" mode="YES" change="150">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.YES.20</response>
            <response type="NEUTRAL" mode="YES" change="140">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.YES.21</response>
            <response type="NEUTRAL" mode="MAYBE" change="0">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.MAYBE.22</response>
            <response type="NEUTRAL" mode="MAYBE" change="0">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.MAYBE.23</response>
            <response type="NEUTRAL" mode="MAYBE" change="0">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.MAYBE.24</response>
            <response type="NEUTRAL" mode="NO" change="-100">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.NO.25</response>
            <response type="NEUTRAL" mode="NO" change="-120">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.NO.26</response>
            <response type="NEUTRAL" mode="NO" change="-150">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.NEUTRAL.NO.27</response>
            <response type="HUMBLE" mode="YES" change="80">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.28</response>
            <response type="HUMBLE" mode="YES" change="60">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.29</response>
            <response type="HUMBLE" mode="YES" change="50">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.YES.30</response>
            <response type="HUMBLE" mode="MAYBE" notalk="true" change="-50">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.31</response>
            <response type="HUMBLE" mode="MAYBE" notalk="true" change="-50">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.32</response>
            <response type="HUMBLE" mode="MAYBE" notalk="true" change="-50">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.MAYBE.33</response>
            <response type="HUMBLE" mode="NO" notalk="true" change="-200">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.34</response>
            <response type="HUMBLE" mode="NO" notalk="true" change="-200">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.35</response>
            <response type="HUMBLE" mode="NO" notalk="true" change="-200">diplomacy.FreeNations.DIPLOMATIC_RELATIONS.AGGRESSIVE.NO.36</response>
        </negotiate>
        <negotiate type="MONEY">
            <approach type="NEUTRAL">diplomacy.FreeNations.MONEY.37</approach>
            <response type="NEUTRAL" mode="YES" change="120">diplomacy.FreeNations.MONEY.YES.38</response>
            <response type="NEUTRAL" mode="YES" change="80">diplomacy.FreeNations.MONEY.YES.39</response>
            <response type="NEUTRAL" mode="YES" change="60">diplomacy.FreeNations.MONEY.YES.40</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-50">diplomacy.FreeNations.MONEY.NO.41</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-100">diplomacy.FreeNations.MONEY.NO.42</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-150">diplomacy.FreeNations.MONEY.NO.43</response>
        </negotiate>
        <negotiate type="TRADE">
            <approach type="NEUTRAL">diplomacy.FreeNations.TRADE.44</approach>
            <response type="NEUTRAL" mode="YES" change="150">diplomacy.FreeNations.TRADE.YES.45</response>
            <response type="NEUTRAL" mode="YES" change="130">diplomacy.FreeNations.TRADE.YES.46</response>
            <response type="NEUTRAL" mode="YES" change="110">diplomacy.FreeNations.TRADE.YES.47</response>
            <response type="NEUTRAL" mode="NO" change="0">diplomacy.FreeNations.TRADE.NO.48</response>
            <response type="NEUTRAL" mode="NO" change="-20">diplomacy.FreeNations.TRADE.NO.49</response>
            <response type="NEUTRAL" mode="NO" change="-20">diplomacy.FreeNations.TRADE.NO.50</response>
        </negotiate>
        <negotiate type="ALLY">
            <approach type="NEUTRAL">diplomacy.FreeNations.ALLY.51</approach>
            <response type="NEUTRAL" mode="YES" change="150">diplomacy.FreeNations.ALLY.YES.52</response>
            <response type="NEUTRAL" mode="YES" change="120">diplomacy.FreeNations.ALLY.YES.53</response>
            <response type="NEUTRAL" mode="YES" change="100">diplomacy.FreeNations.ALLY.YES.54</response>
            <response type="NEUTRAL" mode="NO" change="-40">diplomacy.FreeNations.ALLY.NO.55</response>
            <response type="NEUTRAL" mode="NO" change="-50">diplomacy.FreeNations.ALLY.NO.56</response>
            <response type="NEUTRAL" mode="NO" change="-90">diplomacy.FreeNations.ALLY.NO.57</response>
        </negotiate>
        <negotiate type="DARGSLAN">
            <approach type="NEUTRAL">diplomacy.FreeNations.DARGSLAN.58</approach>
            <response type="NEUTRAL" mode="YES" change="200">diplomacy.FreeNations.DARGSLAN.YES.59</response>
            <response type="NEUTRAL" mode="YES" change="180">diplomacy.FreeNations.DARGSLAN.YES.60</response>
            <response type="NEUTRAL" mode="YES" change="160">diplomacy.FreeNations.DARGSLAN.YES.61</response>
            <response type="NEUTRAL" mode="NO" change="0">diplomacy.FreeNations.DARGSLAN.NO.62</response>
            <response type="NEUTRAL" mode="NO" change="0">diplomacy.FreeNations.DARGSLAN.NO.63</response>
            <response type="NEUTRAL" mode="NO" change="0">diplomacy.FreeNations.DARGSLAN.NO.64</response>
        </negotiate>
        <negotiate type="SURRENDER">
            <approach type="NEUTRAL">diplomacy.FreeNations.SURRENDER.65</approach>
            <response type="NEUTRAL" mode="YES" notalk="true" change="0">diplomacy.FreeNations.SURRENDER.YES.66</response>
            <response type="NEUTRAL" mode="YES" notalk="true" change="0">diplomacy.FreeNations.SURRENDER.YES.67</response>
            <response type="NEUTRAL" mode="YES" notalk="true" change="0">diplomacy.FreeNations.SURRENDER.YES.68</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-200">diplomacy.FreeNations.SURRENDER.NO.69</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-200">diplomacy.FreeNations.SURRENDER.NO.70</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-200">diplomacy.FreeNations.SURRENDER.NO.71</response>
        </negotiate>
        <terminate>diplomacy.FreeNations.terminate.72</terminate>
        <call type="SURRENDER">
            <approach type='AGGRESSIVE'>diplomacy.FreeNations.SURRENDER.73</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.SURRENDER.74</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.SURRENDER.75</approach>
        </call>
        <call type="ALLIANCE">
            <approach type='AGGRESSIVE'>diplomacy.FreeNations.ALLIANCE.76</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.ALLIANCE.77</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.ALLIANCE.78</approach>
        </call>
        <call type="PEACE">
            <approach type='AGGRESSIVE'>diplomacy.FreeNations.PEACE.79</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.PEACE.80</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.PEACE.81</approach>
        </call>
        <call type="MONEY">
            <approach type='AGGRESSIVE'>diplomacy.FreeNations.MONEY.82</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.MONEY.83</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.MONEY.84</approach>
        </call>
        <call type="WAR">
            <approach type='AGGRESSIVE'>diplomacy.FreeNations.WAR.85</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.WAR.86</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.WAR.87</approach>
        </call>
        <call type="RESIGN">
            <approach type='AGGRESSIVE'>diplomacy.FreeNations.RESIGN.88</approach>
            <approach type="NEUTRAL">diplomacy.FreeNations.RESIGN.89</approach>
            <approach type="HUMBLE">diplomacy.FreeNations.RESIGN.90</approach>
        </call>
    </player>

```

Original comment by `akarn...@gmail.com` on 19 Jun 2012 at 4:18
- Changed state: **Accepted**
- Added labels: **Type-Enhancement**, **Priority-Low**, **Milestone-0.96**
- Removed labels: **Type-Defect**, **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Could you send me one that is complete, to have an example?
```

Original comment by `gharr...@gmail.com` on 19 Jun 2012 at 4:27

**Comment by GoogleCodeExporter** [comment]
```
Sure.
```

Original comment by `akarn...@gmail.com` on 19 Jun 2012 at 4:34

Attachments:
- [garthog_diplomacy.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-567/comment-3/garthog_diplomacy.zip)

**Comment by GoogleCodeExporter** [comment]
```
OK, I'm on it.
```

Original comment by `gharr...@gmail.com` on 19 Jun 2012 at 4:46

**Comment by GoogleCodeExporter** [comment]
```
Meanwhile,could  somebody make a dipfej9.ani by using the garthog.png from the 
database? I'm not saying that it should be Norbert, but it would be nice of him 
:)
```

Original comment by `gharr...@gmail.com` on 19 Jun 2012 at 10:34

**Comment by GoogleCodeExporter** [comment]
```
I'll do the head since it requires precise frame numbers and alignments.
```

Original comment by `akarn...@gmail.com` on 20 Jun 2012 at 7:00

Attachments:
- [diplomacy_hu.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-567/comment-6/diplomacy_hu.zip)

**Comment by GoogleCodeExporter** [comment]
```
Here you go. After you and the other Hungarians do the necessary corrections, I 
can translate it to English.

-------------------

<player id="Garthog">
        <negotiate type="DIPLOMATIC_RELATIONS">
            <approach type="AGGRESSIVE">Javasoljuk, hogy a Garthog Birodalom gondolkozzon el egy, a Galaktikus Birodalommal kötött szövetségen. Ellenkező esetben a következő akit hívni fogok, a flotta lesz.</approach>
            <approach type="AGGRESSIVE">A velünk kötött szövetség nem kötelező, de erősen javasolt az alsóbbrendű népek számára...</approach>
            <approach type="AGGRESSIVE">Aki nincs velünk, az ellenünk van, Tanácsos. Remélem, ért engem?</approach>
            <approach type="NEUTRAL">Sergeink egymagukban is erősek, de együtt megállíthatatlanok lennénk. Mit gondol erről, Tanácsos?</approach>
            <approach type="NEUTRAL">Tegyük félre ellentéteinket, hiszen együtt az egész galaxist meghódíthatnánk!</approach>
            <approach type="NEUTRAL">Mi értelme ennek a hadakozásnak, amit még dédapáink kezdtek el? Ha szövetségre lépnénk, végre mind koncentrálhatnánk igazi ellenségeinkre.</approach>
            <approach type="HUMBLE">Felajánljuk baráti jobbunkat a hatalmas Garthog Birodalomnak.</approach>
            <approach type="HUMBLE">Megtisztelve éreznénk magunkat, ha a Garthogok oldalán harcolhatnánk a többi szánalmas faj ellen.</approach>
            <approach type="HUMBLE">Ha két ilyen erős birodalom összefogna, megállíthatatlanok lennénk, Tanácsos!</approach>
            <response type="AGGRESSIVE" mode="YES" change="150">Egyetértünk, egy ilyen szövetség előnyökkelk járna mindkét fél számára.</response>
            <response type="AGGRESSIVE" mode="YES" change="120">A Tanács a felterjesztést kis többséggel ugyan, de elfogadta.</response>
            <response type="AGGRESSIVE" mode="YES" change="100">Bebizonyítottad, hogy érdemes vagy a tiszteletünkre. Ám legyen!</response>
            <response type="AGGRESSIVE" mode="MAYBE" change="-80">Népünk nehezen felejt, Admirális. Meglátom, mit tehetek.</response>
            <response type="AGGRESSIVE" mode="MAYBE" change="-70">Továbbra is nagy az ellenállás a földiekkel szemben. Nem tudom véghez lehet-e vinni ilyen egyezményt.</response>
            <response type="AGGRESSIVE" mode="MAYBE" change="-50">Gondolkozunk a dologról.</response>
            <response type="AGGRESSIVE" mode="NO" notalk="true" change="-150">Mit hiszel, ki vagy földi? Nincs szükségünk tőled semmire!</response>
            <response type="AGGRESSIVE" mode="NO" notalk="true" change="-250">Nevetséges emberi féreg, fogsz te még nekem könyörögni.</response>
            <response type="AGGRESSIVE" mode="NO" notalk="true" change="-270">Személyesen fogom kivágni a nyelved, amiért így beszélsz velem!</response>
            <response type="NEUTRAL" mode="YES" change="160">Lehet róla szó.</response>
            <response type="NEUTRAL" mode="YES" change="150">Sosem gondoltam volna, hogy eljön ez a nap, de a Tanács megszavazta a földiek és a Garthogok közötti szövetség megkötését.</response>
            <response type="NEUTRAL" mode="YES" change="140">Elfogadjuk a javaslatot, egy ideig...</response>
            <response type="NEUTRAL" mode="MAYBE" change="0">Nem vagyok biztos benne, hogy ez a valaha volt legjobb ötleted, ember.</response>
            <response type="NEUTRAL" mode="MAYBE" change="0">A Tanács esetleg jövőre fontolóra veszi a dolgot.</response>
            <response type="NEUTRAL" mode="MAYBE" change="0">Talán egyszer ennek is eljön az ideje.</response>
            <response type="NEUTRAL" mode="NO" change="-100">Külön utakat jár a két faj, nincs érdekünk veletek közösködni.</response>
            <response type="NEUTRAL" mode="NO" change="-120">Ezt most inkább kihagynánk, Admirális.</response>
            <response type="NEUTRAL" mode="NO" change="-150">Esetleg máskor.</response>
            <response type="HUMBLE" mode="YES" change="80">Rendben van, amúgy is sajnálnánk rátok pazarolni a csatahajóinkat.</response>
            <response type="HUMBLE" mode="YES" change="60">Amúgy is kár belétek a rakéta. Legalább lesz időnk harcolni méltó ellenségekkel.</response>
            <response type="HUMBLE" mode="YES" change="50">Végre megtaláltad a megfelelő hangnemet. Legyen, jöjjön létre szövetség a két nép között!</response>
            <response type="HUMBLE" mode="MAYBE" notalk="true" change="-50">Korai lenne még erről beszélni.</response>
            <response type="HUMBLE" mode="MAYBE" notalk="true" change="-50">Ebben a fázisban még nem tudunk nyilatkozni az ügyben.</response>
            <response type="HUMBLE" mode="MAYBE" notalk="true" change="-50">Kiforratlannak tartjuk az ötletét.</response>
            <response type="HUMBLE" mode="NO" notalk="true" change="-200">A helyedben visszaadnám az admirálisi megbizatásomat, pincsi.</response>
            <response type="HUMBLE" mode="NO" notalk="true" change="-200">Nevetséges vagy te is és amit mondasz, az is!</response>
            <response type="HUMBLE" mode="NO" notalk="true" change="-200">Hiába könyörögsz, földi, nem lesz kegyelem!</response>
        </negotiate>
        <negotiate type="MONEY">
            <approach type="NEUTRAL">Úgy döntöttünk, hogy felajánlunk %s creditet a Garthog Birodalom megsegítésére.</approach>
            <response type="NEUTRAL" mode="YES" change="120">Nagylelkűséged nem marad hála nélkül!</response>
            <response type="NEUTRAL" mode="YES" change="80">Bár nekünk is van bőven pénzünk, azért köszönjük a felajánlást.</response>
            <response type="NEUTRAL" mode="YES" change="60">A segély összegét Garthog árvák megsegítésére fogjuk felhasználni.</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-50">Számalmasak vagytok, egytől-egyig. Tartsátok meg a pénzetek!</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-100">És mégis mit kezdenénk ezzel a pénzzel? Ennél még én is többet keresek!</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-150">Tartsd meg a játékpénzed, ember!</response>
        </negotiate>
        <negotiate type="TRADE">
            <approach type="NEUTRAL">Ha kereskedelmi egyezményt kötnénk, több pénz jutna mindkét nép számára technológia kifejlesztésére.</approach>
            <response type="NEUTRAL" mode="YES" change="150">Jól mondja, Admirális. A kereskedelem pénz, a pénz pedig technológia.</response>
            <response type="NEUTRAL" mode="YES" change="130">Megpróbálhatjuk, de nem ajánlom, hogy átverjenek.</response>
            <response type="NEUTRAL" mode="YES" change="110">Látunk fantáziát az ötletben.</response>
            <response type="NEUTRAL" mode="NO" change="0">Nincs szükségünk ilyen emberi bohócságokra.</response>
            <response type="NEUTRAL" mode="NO" change="-20">A kereskedelemben semmi pénz nincs, csak időfecsérlés.</response>
            <response type="NEUTRAL" mode="NO" change="-20">Ismerjük a taktikát, Admirális. A kereskedőhajóik nyüzsögnek a kémektől. A válaszunk: Nem.</response>
        </negotiate>
        <negotiate type="ALLY">
            <approach type="NEUTRAL">A %s folyamatosan megsérti közös határaink integritását. Ideje leszámolni velük!</approach>
            <response type="NEUTRAL" mode="YES" change="150">A %s hajói rendszeresen a szektorunkban portyáznak. Halál rájuk!</response>
            <response type="NEUTRAL" mode="YES" change="120">Egyetértünk abban, hogy ilyen arcátlanságot nem lehet tűrni.</response>
            <response type="NEUTRAL" mode="YES" change="100">Tanácsunk úgy véli, hogy a %s seregeit közös erővel heteken belül porrá zúzhatjuk.</response>
            <response type="NEUTRAL" mode="NO" change="-40">Túl sok fronton csatázunk már most is. Nincs szükség még egyre.</response>
            <response type="NEUTRAL" mode="NO" change="-50">Nem fogjuk helyettetek megvívni a harcaitokat!</response>
            <response type="NEUTRAL" mode="NO" change="-90">Inkább végignézzük, ahogy a %s a földbe tipossa szánalmas birodalmatokat.</response>
        </negotiate>
        <negotiate type="DARGSLAN">
            <approach type="NEUTRAL">A Dargslanok egyre csak terjeszkednek és túl erősek ahhoz, hogy egyedül megállítsuk őket. Össze kell fognunk ellenük mindannyiunk jövője érdekében!</approach>
            <response type="NEUTRAL" mode="YES" change="200">A Dargslan Királyság pestisként fertőzi a galaxist. Segítünk nektek a kór megállításában.</response>
            <response type="NEUTRAL" mode="YES" change="180">Igaza van, Admirális. Ki kell iratni őket írmagostul!</response>
            <response type="NEUTRAL" mode="YES" change="160">Együtt valóban lehet esélyünk ellenük.</response>
            <response type="NEUTRAL" mode="NO" change="0">Boldonok lennénk magunkra haragítani a Dargslanokat.</response>
            <response type="NEUTRAL" mode="NO" change="0">Kizárt dolog, Admirális. Nem ettünk meszet.</response>
            <response type="NEUTRAL" mode="NO" change="0">Ostobaság lenne egy ilyen esélytelen háborúba bocsátkozni.</response>
        </negotiate>
        <negotiate type="SURRENDER">
            <approach type="NEUTRAL">Bár volt pár jobb pillanata, a Garthog Birodalom kétség kívül a bukás szélén áll. A civil áldozatok csökkentése érdekében felajánljuk a megadás lehetőségét.</approach>
            <response type="NEUTRAL" mode="YES" notalk="true" change="0">Valóban nincs más választásunk, megadjuk magunkat.</response>
            <response type="NEUTRAL" mode="YES" notalk="true" change="0">Fájó szívvel és keserű szájízzel, de megadjuk magunkat.</response>
            <response type="NEUTRAL" mode="YES" notalk="true" change="0">Szégyenteli nap ez a Garthogok számára. Megadjuk magunkat.</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-200">Ostoba senkiházi! Könyörögsz majd te még nekem az életedért!</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-200">Nincs szánalmasabb, mint a hazug emberfajzat.</response>
            <response type="NEUTRAL" mode="NO" notalk="true" change="-200">Előbb lövöm le magam, mint hogy a te rabszolgád legyek, kutya!</response>
        </negotiate>
        <terminate>diplomacy.FreeNations.terminate.72</terminate>
        <call type="SURRENDER">
            <approach type='AGGRESSIVE'>Megadjuk magunkat, de csak azért, hogy utána belülről bomlaszthassuk a Birodalmat.</approach>
            <approach type="NEUTRAL">Szégyen ez a nap minden Garthog számára, de nincs más választásunk, megadjuk magunkat.</approach>
            <approach type="HUMBLE">Az igazi harcos, tudja mikor nincs értelme tovább harcolni. Ez a pillanat most jött el a Garthogok számára.</approach>
        </call>
        <call type="ALLIANCE">
            <approach type='AGGRESSIVE'>Hajlandók vagyunk szövetségre lépni a földi népekkel.</approach>
            <approach type="NEUTRAL">A Tanács megszavazta a két birodalom közötti szövetség megkötését.</approach>
            <approach type="HUMBLE">Bebizonyítottad, hogy érdemes téged emberszámba venni. A Garthog Birodalom kész a két nép közötti szövetség megkötésére.</approach>
        </call>
        <call type="PEACE">
            <approach type='AGGRESSIVE'>Ha békét köthetnénk, nem kellene több Garthognak meghalnia. És embernek sem...</approach>
            <approach type="NEUTRAL">Értelmetlen ez a háború, úgysem fog egyikünk sem nyerni. Nem lenne jobb békét kötni, Admirális?</approach>
            <approach type="HUMBLE">Admirális, fontoja meg a békekötés lehetőségét a két nép között!</approach>
        </call>
        <call type="MONEY">
            <approach type='AGGRESSIVE'>Ha kapunk %s creditet, akkor talán még megéritek a holnapot.</approach>
            <approach type="NEUTRAL">Sok Garthog azt mondja, hogy a veletek kötött szövetségnek nincs értelme. Talán %s credittel meg tudnám őket győzni az ellenkezőjéről.</approach>
            <approach type="HUMBLE">Az értetek vívott harcban sok veszteséget szenvedtünk. %s credit feledteté bánatunkat...</approach>
        </call>
        <call type="WAR">
            <approach type='AGGRESSIVE'>Halál az emberfajzatokra!</approach>
            <approach type="NEUTRAL">Nincs más megoldás, mint hogy felégessünk minden bolygót, amin valaha ember járt.</approach>
            <approach type="HUMBLE">Fájó szívvel, de ki kell, hogy irtsuk ezt a fertőzést, amit a néped képvisel a galaktikában.</approach>
        </call>
        <call type="RESIGN">
            <approach type='AGGRESSIVE'>Ez az utolsó esélye, Admirális! Ha most nem adja meg magát, az írmagját is kiirtjuk a nyomorult földi népnek!</approach>
            <approach type="NEUTRAL">Ha nem adja fel most a háborút, páholyból nézheti végig, amint a maradék bolygóit is lángokba borítjuk!</approach>
            <approach type="HUMBLE">Kap egy utolsó esélyt, Admirális. Ne mondja senki, hogy a Garthog egy nem civilizált faj.</approach>
        </call>
    </player>
```

Original comment by `gharr...@gmail.com` on 21 Jun 2012 at 9:31

**Comment by GoogleCodeExporter** [comment]
```
I have proof-read it and corrected a few errors. You can go ahead with the 
translation. I need to find someone who can do german translation...
```

Original comment by `akarn...@gmail.com` on 22 Jun 2012 at 8:00

Attachments:
- [diplomacy_garthog.zip](https://storage.googleapis.com/google-code-attachments/open-ig/issue-567/comment-8/diplomacy_garthog.zip)

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 23 Jun 2012 at 11:22
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
I translated it to english and copied it to german for now.
```

Original comment by `akarn...@gmail.com` on 13 Jul 2012 at 10:51
- Changed state: **SVN**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 13 Jul 2012 at 1:34
- Changed state: **Fixed**
