### ISSUE TITLE
i cannot defend the trader in campaign september 21, futhermore the game generally has some problems to trigger many plot-events

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#590]
```
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
http://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0_05
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows 7, x86, 6.1
   Game version: 0.95.016
   Command line: [-memonce, -en]
   Available memory: 229 MB
   Maximum memory: 742 MB
   Parallelism: 4
   Startup language: hu
A crash save has been created, please attach it in the issue report (zipped).
----
java.util.NoSuchElementException
    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at java.util.Collections.min(Unknown Source)
    at hu.openig.mechanics.ExplorationPlanner.setExplorationTarget(ExplorationPlanner.java:300)
    at hu.openig.mechanics.ExplorationPlanner.plan(ExplorationPlanner.java:63)
    at hu.openig.mechanics.Planner.run(Planner.java:189)
    at hu.openig.mechanics.AI.manage(AI.java:600)
    at hu.openig.screen.CommonResources.runAI(CommonResources.java:607)
    at hu.openig.screen.CommonResources$20.run(CommonResources.java:586)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

```

Original issue reported on code.google.com by `andreas....@gmx.de` on 27 Jun 2012 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
Thank you for reporting. Could you be more specific in:

- defend the trader: is it a hard battle or you don't reach the trader in time?
- plot events: which events are these?

Please upload a save (zipped) demonstrating the problems.
```

Original comment by `akarn...@gmail.com` on 27 Jun 2012 at 10:03
- Changed state: **Accepted**
- Added labels: **Milestone-0.95.200**

**Comment by GoogleCodeExporter** [comment]
```
Hi there!
Unfortunately the names of the savefiles (dates) don't match the names of the 
saves in the game, so I'm unable to select the correct save.
Right now the game seems to work, as soon as I encounter another problem I will 
post it here with the coorect save. I'll just delete all older saves and then 
I#ll know which one to pick.

Thanks for making this game of my youth enjoyable again, it still captivates me.

Andreas 
```

Original comment by `andreas....@gmx.de` on 6 Jul 2012 at 9:33

**Comment by GoogleCodeExporter** [comment]
```
hi there,

by deleting all the other saves I could single out the one i suspect to be the  
faulty one. still I'm not totally sure if it is the one I reported here, I 
encountered many crashes and many untriggered plot events, therefore i had many 
restarts of the game, thy didn't alway apear again, kind of impredidictable...
I attach the save now.
Is it normal that the game does not proceed to trigger next events, if you do 
not set all the builidngs on Achilles (in the very beginning of the game) on 
active and by that fulfill the very first task? I encountered that many times 
and it made it possible to develop my relm without being challenged by new 
tasks...

Andreas
```

Original comment by `andreas....@gmx.de` on 6 Jul 2012 at 9:45

Attachments:
- [save-2012-06-25-13-09-31-329.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-590/comment-3/save-2012-06-25-13-09-31-329.xml)
- [info-2012-06-25-13-09-31-329.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-590/comment-3/info-2012-06-25-13-09-31-329.xml)
- [profile.xml](https://storage.googleapis.com/google-code-attachments/open-ig/issue-590/comment-3/profile.xml)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the save. It only indicates that you need to complete the Achilles 
mission, and no sign of defend the trader at all. In fact, all three are 
completed successfully.

Currently, you need to complete the Achilles related missions in order to 
trigger the events for the next level. I haven't decided to force a much 
earlier trigger, because:
- you could enter lvl2 with Achilles still in ruins and you need to still 
allocate money for it instead of production and expansion,
- some users liked the opportunity to buff-out before lvl2,
- still not sure how the original handled this.


```

Original comment by `akarn...@gmail.com` on 6 Jul 2012 at 10:32

**Comment by GoogleCodeExporter** [comment]
```
The crash is resolved. The case for plot continuity is moved to a separate 
issue. Not enough information regarding the trader.
```

Original comment by `akarn...@gmail.com` on 18 Jul 2012 at 1:06
- Changed state: **SVN**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 21 Jul 2012 at 6:31
- Changed state: **Fixed**
