### ISSUE TITLE
The game needs hungarian pack installed to start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#716]
```
Without it some audio files are missing and launcher refuses to start.

A crash save may have been created. Please attach it in the issue report 
(zipped).
java.lang.AssertionError: Missing resource: hu ui/add_production
    at hu.openig.sound.Sounds.<init>(Sounds.java:103)
    at hu.openig.screen.CommonResources.init(CommonResources.java:348)
    at hu.openig.screen.CommonResources.<init>(CommonResources.java:227)
    at hu.openig.Startup$6.run(Startup.java:250)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

```

Original issue reported on code.google.com by `jalich` on 23 Mar 2013 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
Hi. Could you please run the Other > Verify install command? I couldn't 
reproduce the issue. I get proper warnings if the language is wrongly selected 
in the launcher or when starting the game. This issue might have occurred in 
earlier versions, please make sure you have the latest launcher.
```

Original comment by `akarn...@gmail.com` on 23 Mar 2013 at 10:23
- Changed state: **Clarify**

**Comment by GoogleCodeExporter** [comment]
```
Yes I did verify.
Basically english version of the game needs hungarian GUI sounds which are 
missing from english pack.

If you get a clean install with only enlighs pack, verify passes but game will 
crash on startup with this stacktrace.
```

Original comment by `jalich` on 23 Mar 2013 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Could you post the full error message? You might also try and delete 
open-ig-config.xml.
```

Original comment by `akarn...@gmail.com` on 23 Mar 2013 at 10:34

**Comment by GoogleCodeExporter** [comment]
```
I'm closing this. If the issue reappears, please open a new issue.
```

Original comment by `akarn...@gmail.com` on 28 Feb 2014 at 7:46
- Changed state: **Closed**
