### ISSUE TITLE
There should be some guide for how to start working on this project

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#744]
```
While the bug tracker is inappropriate for the topic at hand, it appears to be 
a very successful way for contacting you. :P
Do you want to accept other contributors in the project (and not just art 
people but coders) ? If so, I'd like there to be more info about how to start 
working. I managed the easier steps alone and tried debugging through the code 
but didn't come very far.
I like contributing to a few other OOS projects; however, none of them is in 
java so far.
```

Original issue reported on code.google.com by `anonymis...@arcor.de` on 7 Jun 2013 at 9:37

**Comment by GoogleCodeExporter** [comment]
```
Many managed to find my email address.

Three things:
1) You'll need at least medium level Java programming knowledge. If you come 
from C#, that is easier to switch over.
2) Most time you'll spend is to locate things. You haven't told me what you 
want to work on, but if I assume the things in your issues, that requires deep 
Open-IG knowledge.
3) Coders tend to disappear on me. They manage to get one small feature done, 
and then perhaps give up as it might be not as rewarding as they thought.
```

Original comment by `akarn...@gmail.com` on 8 Jun 2013 at 6:28
- Changed state: **Question**

**Comment by GoogleCodeExporter** [comment]
```
I rather come from C++. I had java classes but that's most likely just very 
basic knowledge. I never worked with a gui for instance, just some command line 
programs to teach us basic principles. OOP, pointers and such. Well, if I don't 
cope with it I can't learn.
As for disappearing coders, that's a general problem. It happens all the time 
in the projects I know. You can expect only a few out of many people to stay 
for more than a few months.
```

Original comment by `anonymis...@arcor.de` on 8 Jun 2013 at 2:53

**Comment by GoogleCodeExporter** [comment]
```
If you are good with algorithms, there are a few issues you could help with. 
For example, the issue with the spacewar overlapping units. solutions include 
variant of A* pathfinding which handles 2x2 and 3x3 objects, not just the usual 
1x1; flow fields based approach (I heard that C++ examples are plenty).
If you work out algorithms in C++, I can do the translation to Java.

What I won't be able to do is teach you Java, nor is it likely that I write a 
developer documentation. It's simply too much time and not as much fun as 
actually developing the game.
```

Original comment by `akarn...@gmail.com` on 8 Jun 2013 at 4:55

**Comment by GoogleCodeExporter** [comment]
```
good with algorithms: I very much doubt I am, and if I do one I definitely 
would want to code it myself no matter what language, debug through it, see its 
effects, test it. Seeing its effects is the fun part then.
I don't think I need to be taught some language itself, actually. There's 
enough info on the web.
I'm perhaps best at noticing bugs and tracking them down.

Well, here's where I am:
I imported the open-ig project as an existing project in eclipse as you 
recommend and copied the resources from the normal installation as it asked for 
them (is that the way it's supposed to be done ?)
Starting a human vs ai under the debugger fails with the following stack trace

java.lang.IllegalArgumentException: Building type not supported here: Outer 14 
- ColonyHub
    at hu.openig.model.Planet.build(Planet.java:903)
    at hu.openig.mechanics.AutoBuilder.construct(AutoBuilder.java:440)
    at hu.openig.mechanics.DefaultAIControls.actionPlaceBuilding(DefaultAIControls.java:228)
    at hu.openig.mechanics.ColonyPlanner$21.invoke(ColonyPlanner.java:766)
    at hu.openig.mechanics.AI.apply(AI.java:140)
    at hu.openig.screen.CommonResources$20.run(CommonResources.java:653)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

once that the ai tries to build its colony hub. Breakpoint-catching execution 
right before where that exception is thrown doesn't work, so something about my 
setup seems wrong. I can debug through the startup class but only until it's 
using the ProcessBuilder.
```

Original comment by `anonymis...@arcor.de` on 8 Jun 2013 at 9:12

**Comment by GoogleCodeExporter** [comment]
```
You need to set the memory parameters of the run settings. Drop down the debug 
icon and go for Debug Configurations. Locate the Startup run settings, then on 
the Arguments page, set program arguments to 

-memonce

the VM arguments to

-Xmx768M

This way, the game won't restart itself with exactly these parameters and you 
loosing the debug capability.
```

Original comment by `akarn...@gmail.com` on 8 Jun 2013 at 9:32

**Comment by GoogleCodeExporter** [comment]
```
Thanks, that worked :).
Exceptions still occur; seems it's searching for ColonyHub but there's only a 
MainBuilding. Do I perhaps need the english data pack, or is it just that the 
current trunk is buggy ? If so, I just use the last stable branch or so, for 
finding my way.
```

Original comment by `anonymis...@arcor.de` on 8 Jun 2013 at 10:53

**Comment by GoogleCodeExporter** [comment]
```
Could we please switch over to email?

I don't get this exception in the head, so it might be a setup error.
- Did you place the zip files into the root folder of the project?
- What game are you starting and with what settings?
```

Original comment by `akarn...@gmail.com` on 9 Jun 2013 at 8:00
