### ISSUE TITLE
game won't launch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#748]
```
Game version: 0.95.130


Operating System: Windows 8 64bit


Java runtime version: 1.7.0_05


Installed using the Launcher? Yes


Game language (en, hu, de): EN


What steps will reproduce the problem?
1. Install the game using the launcher
2. Press "Run Game"
3. First time launch comes up
4. After ok nothing happens

or

1. tried launching game using open-ig-0.95.130.jar
2. "Unable to locate some game resources" using the launcher to fix it will 
verify the files, but still can't launch. When no is pressed nothing happens 
and this error report is on screen :

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0_05
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows NT (unknown), x86, 6.2
   Game version: 0.95.130
   Command line: [-memonce]
   Available memory: 57 MB
   Maximum memory: 742 MB
   Parallelism: 8
   Language: hu
   Date and time: 2013-07-01T22:49:48.090Z
----
A crash save may have been created. Please attach it in the issue report 
(zipped).
java.lang.AssertionError: Missing resource: hu ui/add_production
    at hu.openig.sound.Sounds.<init>(Sounds.java:103)
    at hu.openig.screen.CommonResources.init(CommonResources.java:348)
    at hu.openig.screen.CommonResources.<init>(CommonResources.java:227)
    at hu.openig.Startup$6.run(Startup.java:250)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)



```

Original issue reported on code.google.com by `chriseil...@gmail.com` on 1 Jul 2013 at 10:53

Attachments:
- [open-ig.log](https://storage.googleapis.com/google-code-attachments/open-ig/issue-748/comment-0/open-ig.log)

**Comment by GoogleCodeExporter** [comment]
```
Hello, please select Other > Verify install in the launcher.
```

Original comment by `akarn...@gmail.com` on 2 Jul 2013 at 7:34
- Changed state: **Clarify**

**Comment by GoogleCodeExporter** [comment]
```
Done that. Still no changes...
```

Original comment by `chriseil...@gmail.com` on 2 Jul 2013 at 9:16

**Comment by GoogleCodeExporter** [comment]
```
Did you install just the English language pack? I don't know why this happens. 
Please go to Other options > Select language packs and install the Hungarian 
pack.
```

Original comment by `akarn...@gmail.com` on 2 Jul 2013 at 9:51
- Added labels: **Install**

**Comment by GoogleCodeExporter** [comment]
```
Yes, only the english. I have installed the hungarian languagepack now, and 
tried to launch the game in that language with the launcher. No succes. 
However, when I launched
open-ig-0.95.130.jar it played the movies and got me into the main menu. I 
clicked some further with a lot of luck and the game runs. Too bad it is now 
only in Hungarian...


```

Original comment by `chriseil...@gmail.com` on 2 Jul 2013 at 11:25

**Comment by GoogleCodeExporter** [comment]
```
You can hit CTRL+1 in the main menu to switch to English. It is quite odd the 
Launcher doesn't work properly. Do you have the latest Launcher (0.42)? Before 
0.95.130, did you have any previous version of the game?
```

Original comment by `akarn...@gmail.com` on 2 Jul 2013 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
I just found this yesterday and downloaded it from the downloads page. It is 
version 0.42.

The CTRL+1 works. Thanks.
```

Original comment by `chriseil...@gmail.com` on 2 Jul 2013 at 11:44

**Comment by GoogleCodeExporter** [comment]
```
Oh, I think I found the problem. In Run settings, I erased whatever stood in 
Memory. So it is empty now. Now it will launch from the launcher.
```

Original comment by `chriseil...@gmail.com` on 2 Jul 2013 at 12:01

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 11 Mar 2014 at 12:07
- Changed state: **Closed**
