### ISSUE TITLE
IllegalStateException: failed to remove building

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#762]
```
Apparently some AI failed to remove some building. It wasn't me so no "how to 
reproduce" possible here.
Attaching the crash save and the last save from before.

```

Original issue reported on code.google.com by `anonymis...@arcor.de` on 26 Aug 2013 at 9:20

Attachments:
- [save-2013-08-26-23-10-56-000.xml.gz](https://storage.googleapis.com/google-code-attachments/open-ig/issue-762/comment-0/save-2013-08-26-23-10-56-000.xml.gz)
- [save-2013-08-26-23-03-02-328.xml.gz](https://storage.googleapis.com/google-code-attachments/open-ig/issue-762/comment-0/save-2013-08-26-23-03-02-328.xml.gz)

**Comment by GoogleCodeExporter** [comment]
```
Forgot the error report:

   Java version: 1.7.0_04
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows XP, x86, 5.1
   Game version: 0.95.140
   Command line: [-memonce, -de]
   Available memory: 139 MB
   Maximum memory: 742 MB
   Parallelism: 2
   Language: de
   Date and time: 2013-08-26T21:10:55.984Z
----
java.lang.IllegalStateException: Failed to remove building 2493
    at hu.openig.model.Planet.demolish(Planet.java:1315)
    at hu.openig.mechanics.DefaultAIControls.actionDemolishBuilding(DefaultAIControls.java:241)
    at hu.openig.mechanics.ColonyPlanner$25.invoke(ColonyPlanner.java:845)
    at hu.openig.mechanics.AI.apply(AI.java:140)
    at hu.openig.screen.CommonResources$20.run(CommonResources.java:653)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:701)
    at java.awt.EventQueue.access$000(EventQueue.java:102)
    at java.awt.EventQueue$3.run(EventQueue.java:662)
    at java.awt.EventQueue$3.run(EventQueue.java:660)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:671)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

java.lang.IllegalStateException: Failed to remove building 2605
    at hu.openig.model.Planet.demolish(Planet.java:1315)
    at hu.openig.mechanics.DefaultAIControls.actionDemolishBuilding(DefaultAIControls.java:241)
    at hu.openig.mechanics.ColonyPlanner$25.invoke(ColonyPlanner.java:845)
    at hu.openig.mechanics.AI.apply(AI.java:140)
    at hu.openig.screen.CommonResources$20.run(CommonResources.java:653)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:701)
    at java.awt.EventQueue.access$000(EventQueue.java:102)
    at java.awt.EventQueue$3.run(EventQueue.java:662)
    at java.awt.EventQueue$3.run(EventQueue.java:660)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:671)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

java.lang.IllegalStateException: Failed to remove building 390
    at hu.openig.model.Planet.demolish(Planet.java:1315)
    at hu.openig.mechanics.DefaultAIControls.actionDemolishBuilding(DefaultAIControls.java:241)
    at hu.openig.mechanics.ColonyPlanner$25.invoke(ColonyPlanner.java:845)
    at hu.openig.mechanics.AI.apply(AI.java:140)
    at hu.openig.screen.CommonResources$20.run(CommonResources.java:653)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:701)
    at java.awt.EventQueue.access$000(EventQueue.java:102)
    at java.awt.EventQueue$3.run(EventQueue.java:662)
    at java.awt.EventQueue$3.run(EventQueue.java:660)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:671)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

java.lang.IllegalStateException: Failed to remove building 393
    at hu.openig.model.Planet.demolish(Planet.java:1315)
    at hu.openig.mechanics.DefaultAIControls.actionDemolishBuilding(DefaultAIControls.java:241)
    at hu.openig.mechanics.ColonyPlanner$25.invoke(ColonyPlanner.java:845)
    at hu.openig.mechanics.AI.apply(AI.java:140)
    at hu.openig.screen.CommonResources$20.run(CommonResources.java:653)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:701)
    at java.awt.EventQueue.access$000(EventQueue.java:102)
    at java.awt.EventQueue$3.run(EventQueue.java:662)
    at java.awt.EventQueue$3.run(EventQueue.java:660)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:671)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)


```

Original comment by `anonymis...@arcor.de` on 26 Aug 2013 at 9:21

**Comment by GoogleCodeExporter** [comment]
```
Thanks.
```

Original comment by `akarn...@gmail.com` on 27 Aug 2013 at 7:43
- Changed state: **Fixed**
- Added labels: **Component-Logic**

**Comment by GoogleCodeExporter** [comment]
```
Lol, I kinda liked the heavy earthquakes from before r2988. Made the fire 
brigade actually very useful instead of pretty pointless and non-rocky 
non-earth-like planets much more valuable. Since AI seems to have problems 
dealing with earthquakes, what about just disabling them for AI ? Just another 
cheat. It's too easy anyway.
```

Original comment by `anonymis...@arcor.de` on 27 Aug 2013 at 10:34
