### ISSUE TITLE
NullPointerException when moving a fighter into a new fleet

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#765]
```
Game version: 0.95.141
Operating System: xp 32
Java runtime version: jdk1.7.0_04
Installed using the Launcher? yes
Game language de

In the level 2 start save from Issue 764, attempt to divide the main fleet by 
moving one of the fighters into a new fleet. When klicking onto "part and 
finish" the exception throws.
```

Original issue reported on code.google.com by `anonymis...@arcor.de` on 27 Aug 2013 at 3:23

**Comment by GoogleCodeExporter** [comment]
```
Please add the full stacktrace or log of the incident.
```

Original comment by `akarn...@gmail.com` on 27 Aug 2013 at 3:32
- Changed state: **Clarify**

**Comment by GoogleCodeExporter** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at hu.openig.model.InventoryItems.contains(InventoryItems.java:286)
    at hu.openig.screen.items.EquipmentScreen.doEndSplit(EquipmentScreen.java:2439)
    at hu.openig.screen.items.EquipmentScreen$7.invoke(EquipmentScreen.java:332)
    at hu.openig.ui.UIImageButton.doClick(UIImageButton.java:126)
    at hu.openig.ui.UIImageButton.mouse(UIImageButton.java:162)
    at hu.openig.ui.UIContainer.mouse(UIContainer.java:112)
    at hu.openig.screen.ScreenBase.mouse(ScreenBase.java:110)
    at hu.openig.screen.items.EquipmentScreen.mouse(EquipmentScreen.java:1334)
    at hu.openig.GameWindow$MouseActions.invoke(GameWindow.java:1135)
    at hu.openig.GameWindow$MouseActions.mouseReleased(GameWindow.java:1169)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:703)
    at java.awt.EventQueue.access$000(EventQueue.java:102)
    at java.awt.EventQueue$3.run(EventQueue.java:662)
    at java.awt.EventQueue$3.run(EventQueue.java:660)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:676)
    at java.awt.EventQueue$4.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:673)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

```

Original comment by `anonymis...@arcor.de` on 27 Aug 2013 at 7:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 28 Aug 2013 at 7:27
- Changed state: **Fixed**
- Added labels: **Component-Logic**
