### ISSUE TITLE
starting a new game or viewing the intro crashes the game in linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#78]
```
Game version:

0.93.350

Operating System: (e.g., Windows 7 x86, Windows XP 64-bit)

Ubuntu AMD64

Java runtime version: (run java -version)

OpenJDK 6

Installed using the Launcher? (yes, no)

yes

What steps will reproduce the problem?
1. trying to start a new game or viewing the intro
2.
3.


What is the expected output? What do you see instead?

I get an error window and the game shuts down

Please provide any additional information below.

the error window  contains the following output:

An unexpected error occurred.

You should consider submitting an error report via the project issue list:

http://code.google.com/p/open-ig/issues/list

Please include the following diagnostic information followed by the error 
stacktrace(s):

   Java version: 1.6.0_22
   Java vendor: Sun Microsystems Inc. (http://java.sun.com/)
   Java compiler: null (class version: 50.0)
   Operating system: Linux, amd64, 2.6.38-10-generic
   Game version: 0.93.350
   Command line: [-memonce]
   Maximum memory: 568 MB
   Parallelism: 3
----

Exception in thread "Movie Audio" java.lang.IllegalArgumentException: Master 
Gain not supported
    at org.classpath.icedtea.pulseaudio.PulseAudioLine.getControl(PulseAudioLine.java:89)
    at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.getControl(PulseAudioSourceDataLine.java:51)
    at hu.openig.screen.MediaPlayer$1.run(MediaPlayer.java:126)
    at java.lang.Thread.run(Thread.java:679)


```

Original issue reported on code.google.com by `Bruno9...@gmail.com` on 24 Aug 2011 at 3:16

**Comment by GoogleCodeExporter** [comment]
```
The OpenJDK is buggy in this matter. You should try to upgrade to the latest 
version (1.6.0_26) until I implement a fix for this case.
```

Original comment by `akarn...@gmail.com` on 24 Aug 2011 at 8:57
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in 0.93.375
```

Original comment by `akarn...@gmail.com` on 24 Aug 2011 at 2:10
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```


I can see the intro now and get to the game screen, but at the end of the 
cutscene I get the following error:



An unexpected error occurred.

You should consider submitting an error report via the project issue list:

http://code.google.com/p/open-ig/issues/list

Please include the following diagnostic information followed by the error 
stacktrace(s):

   Java version: 1.6.0_22
   Java vendor: Sun Microsystems Inc. (http://java.sun.com/)
   Java compiler: null (class version: 50.0)
   Operating system: Linux, amd64, 2.6.38-10-generic
   Game version: 0.93.375
   Command line: [-memonce]
   Maximum memory: 568 MB
   Parallelism: 3
----
Please include the following diagnostic information followed by the error 
stacktrace(s):

   Java version: 1.6.0_22
   Java vendor: Sun Microsystems Inc. (http://java.sun.com/)
   Java compiler: null (class version: 50.0)
   Operating system: Linux, amd64, 2.6.38-10-generic
   Game version: 0.93.375
   Command line: [-memonce]
   Maximum memory: 568 MB
   Parallelism: 3
----

Exception in thread "UISounds-1" java.lang.IllegalArgumentException: Invalid 
format
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:143)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:100)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:289)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
    at hu.openig.sound.Sounds$3.run(Sounds.java:142)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
Exception in thread "UISounds-3" java.lang.IllegalArgumentException: Invalid 
format
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:143)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:100)
    at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:289)
    at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
    at hu.openig.sound.Sounds$3.run(Sounds.java:142)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
```

Original comment by `Bruno9...@gmail.com` on 25 Aug 2011 at 12:34
