### ISSUE TITLE
java window error but game still running fine.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#882]
```
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0_51
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows 7, x86, 6.1
   Game version: 0.95.180
   Command line: [-memonce]
   Available memory: 25 MB
   Maximum memory: 742 MB
   Parallelism: 8
   Language: fr
   Date and time: 2014-08-31T12:45:49.557Z
----
A crash save may have been created. Please attach it in the issue report 
(zipped).
C:\imperium galactica\save\jerome\save-2014-08-31-14-45-49-571.xml.gz
java.lang.ArrayIndexOutOfBoundsException: -2
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at hu.openig.model.Player.movePrevPlanet(Player.java:199)
    at hu.openig.screen.GameKeyManager.handleDefaultKeyboard(GameKeyManager.java:258)
    at hu.openig.screen.GameKeyManager.keyPressed(GameKeyManager.java:109)
    at java.awt.Component.processKeyEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Window.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
    at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
    at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

________________________________________________________________
Game is installed with launcher, the game works fine.

First crash happened after a few hours of playing.
I was in "information" window, financial info, and then I used "page down" to 
get info of another planet and got this error window (while the game itself, 
continue to work even after this error output)

_________________________________________________________________
Just to tell you apart from that, I really appreciate your work, i loved this 
game and it was pretty easy to play it with your open reimplementation.

A few other bug i noticed:


- Videos of messages are sometimes playing twice at the same time.
- the message panel animation is too slow.
- The french language is apparently not everywhere.
- The french audio are completely out of sync (except intro video), don't know 
if the sync problem occurs for each language, or even dependent of the platform 
and system.

I noticed a few gameplay and features additions in the game, which are all 
great.
I have however one thing I wondered cause it is quite disappointing: Did you 
change the AI system?
For example, it seems the tanks in ground battle does not care about defenses 
and instead of focusing them they destroy civilians buildings, which is very 
disappointing.

One suggestion about the game features you add, since you can upgrade several 
buildings, what about upgrade a ship power and resistance according to its 
experience in combat if it survive, like in command and conquer?



Thanks for your attention and keep up the good work mate, I know it is very 
hard to keep regular motivation on such solo project on old games!


```

Original issue reported on code.google.com by `Jerome.B...@gmail.com` on 31 Aug 2014 at 1:08

**Comment by GoogleCodeExporter** [comment]
```
Hi and thanks for reporting.
- The double play should be fixed. What did you do when you experienced the 
double play?
- The animation speed is matched with the audio length.
- The French translation is incomplete; few people did some of them some time 
ago.
- The audio sync is missing as well, the original had different videos for 
different languages which were cuts of the more detailed hungarian version.
- AI is rewritten from scratch and has no relation with the original. The AI 
sometimes decides to cause damage if it can't win the battle.
```

Original comment by `akarn...@gmail.com` on 31 Aug 2014 at 1:56
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I don't know exactly for the double play, but I think it happens when I do 
something else at the same time i click the message, i can't redo it apparently 
for now, it was at the first two stage of the campaign.

I forgot one critical issue that should be done in my opinion, about the AI:
In space the response is ok, but on the ground, the tanks are almost all the 
time stuck, they can't move all at once, and even sometimes they don't move at 
all during 5 secondes at least. This makes several ground combat almost 
impossible while it should be quite easy with some management.
This wasn't the case in the original and I don't know what is wrong in the java 
implementation, the processors are really fast enough to handle 50 tanks moving 
at the same time :D.




```

Original comment by `Jerome.B...@gmail.com` on 31 Aug 2014 at 4:00

**Comment by GoogleCodeExporter** [comment]
```
What do you mean by not moving? The enemy tanks don't do anything? We have the 
general shortcoming with units moving in a single line, but they move. There is 
a debug key combo of ctrl+shift+d which toggles ground war ai on and off.
```

Original comment by `akarn...@gmail.com` on 31 Aug 2014 at 4:12

**Comment by GoogleCodeExporter** [comment]
```
This is not about the ennemy units, but our own units. If I order my 25 tanks 
to move somewhere, only half will move, Its like the queue is very slow. And 
because of this, if i want to attack a fortress, my tanks are barely to die one 
by one.
```

Original comment by `Jerome.B...@gmail.com` on 31 Aug 2014 at 4:54

**Comment by GoogleCodeExporter** [comment]
```
Group movement is a long standing issue with the game. The workaround is now to 
move small groups only.
```

Original comment by `akarn...@gmail.com` on 31 Aug 2014 at 6:00

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 1 Sep 2014 at 5:40
- Changed state: **SVN**
- Added labels: **Component-Logic**

**Comment by GoogleCodeExporter** [comment]
Original comment by `akarn...@gmail.com` on 1 Sep 2014 at 2:37
- Changed state: **Fixed**
