### ISSUE TITLE
I can not download the game by louncher

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#894]
```
Game version:   Operating System: (e.g., Windows 7 x86, Windows XP 64-bit)   
Java runtime version: (run java -version)   Installed using the Launcher? (yes, 
no)   Game language (en, hu, de):   What steps will reproduce the problem? 1. 
2. 3.   What is the expected output? What do you see instead?   Please provide 
any additional information below.   Please upload any save before and/or after 
the problem happened. Please attach the open-ig.log file found in the 
application's directory. 

Hi! I can not download the game. I double click on open-ig-launcher, but the 
game not download. What I can do?  
```

Original issue reported on code.google.com by `a.konta...@gmail.com` on 29 Oct 2014 at 2:17

**Comment by GoogleCodeExporter** [comment]
```
Have you installed Java? 

http://www.oracle.com/technetwork/articles/javase/index-jsp-138363.html
```

Original comment by `akarn...@gmail.com` on 29 Oct 2014 at 2:23
- Changed state: **Clarify**
- Added labels: **Install**

**Comment by GoogleCodeExporter** [comment]
```
Yes! I installed java jdk-8u25-windows-x64.exe

```

Original comment by `a.konta...@gmail.com` on 29 Oct 2014 at 2:36

Attachments:
- [Новый точечный рисунок.bmp](https://storage.googleapis.com/google-code-attachments/open-ig/issue-894/comment-2/Новый точечный рисунок.bmp)

**Comment by GoogleCodeExporter** [comment]
Original comment by `a.konta...@gmail.com` on 29 Oct 2014 at 2:37

Attachments:
- [Новый точечный рисунок1.bmp](https://storage.googleapis.com/google-code-attachments/open-ig/issue-894/comment-3/Новый точечный рисунок1.bmp)

**Comment by GoogleCodeExporter** [comment]
```
It seems there is a network issue between you and google. Usually the download 
works within a few hours.
```

Original comment by `akarn...@gmail.com` on 29 Oct 2014 at 2:58

**Comment by GoogleCodeExporter** [comment]
```
what can I do?
```

Original comment by `a.konta...@gmail.com` on 29 Oct 2014 at 3:01

**Comment by GoogleCodeExporter** [comment]
```
I work in google network, when I speak with you.
```

Original comment by `a.konta...@gmail.com` on 29 Oct 2014 at 3:04

**Comment by GoogleCodeExporter** [comment]
```
The only thing you can do is to wait a few hours. If it still doesn't work, go 
to the Install wiki page and try downloading the files manually.
```

Original comment by `akarn...@gmail.com` on 29 Oct 2014 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
Can you test your launcher? may be you have old version launcher?
```

Original comment by `a.konta...@gmail.com` on 29 Oct 2014 at 3:28

**Comment by GoogleCodeExporter** [comment]
```
I think that problen is not with internet... (
```

Original comment by `a.konta...@gmail.com` on 29 Oct 2014 at 3:32

**Comment by GoogleCodeExporter** [comment]
```
It works for me but I'm in Hungary. Google uses replication servers around the 
world so there might be some issue from your viewpoint.
```

Original comment by `akarn...@gmail.com` on 29 Oct 2014 at 5:06

**Comment by GoogleCodeExporter** [comment]
```
hi! the problem persists today. I think that it is not internet...
```

Original comment by `a.konta...@gmail.com` on 31 Oct 2014 at 6:48

**Comment by GoogleCodeExporter** [comment]
```
Can you see this directory in your browser?

https://googledrive.com/host/0B4T7ZW3brESKeU1jWnpqMGVnZ0k
```

Original comment by `akarn...@gmail.com` on 31 Oct 2014 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
Yes, I sow it.
```

Original comment by `a.konta...@gmail.com` on 31 Oct 2014 at 9:55

**Comment by GoogleCodeExporter** [comment]
```
Then try downloading the files from this page:

https://code.google.com/p/open-ig/wiki/Install
```

Original comment by `akarn...@gmail.com` on 31 Oct 2014 at 9:58

**Comment by GoogleCodeExporter** [comment]
```
The game is very good, from my childhood! But After one hour plaing the error 
occurred

MissionTime Mission-7-Task-1-Timeout last deallocation: 
java.lang.AssertionError: MissionTime Mission-7-Task-1-Timeout
    at hu.openig.scripting.MainCampaignScripting.clearMissionTime(MainCampaignScripting.java:992)
    at hu.openig.scripting.missions.Mission.clearMission(Mission.java:1009)
    at hu.openig.scripting.missions.Mission7.completeTaskN(Mission7.java:292)
    at hu.openig.scripting.missions.Mission7.spacewarFinishTraderVsPirate(Mission7.java:266)
    at hu.openig.scripting.missions.Mission7.onSpacewarFinish(Mission7.java:318)
    at hu.openig.scripting.MainCampaignScripting.onSpacewarFinish(MainCampaignScripting.java:900)
    at hu.openig.screen.items.SpacewarScreen.concludeBattle(SpacewarScreen.java:4420)
    at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3760)
    at hu.openig.screen.items.SpacewarScreen$8.invoke(SpacewarScreen.java:3012)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:869)
    at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:245)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$400(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

what could it be?
```

Original comment by `a.konta...@gmail.com` on 2 Nov 2014 at 6:21

**Comment by GoogleCodeExporter** [comment]
```
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.8.0_25
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 7, amd64, 6.1
   Game version: 0.95.197
   Command line: []
   Available memory: 49 MB
   Maximum memory: 1819 MB
   Parallelism: 4
   Language: ru
   Date and time: 2014-11-02T06:23:19.544Z
----
A crash save may have been created. Please attach it in the issue report 
(zipped).
    <entry key='groundwar.retreat_confirm.tooltip'></entry>

```

Original comment by `a.konta...@gmail.com` on 2 Nov 2014 at 6:23

**Comment by GoogleCodeExporter** [comment]
```
The first one is just a script warning for me, doesn't really affect the 
gameplay. The second indicates I forgot a translation.

It appears you were able to run the game so I'm going to close this issue and 
create new ones.
```

Original comment by `akarn...@gmail.com` on 2 Nov 2014 at 8:47
- Changed state: **Closed**
