### ISSUE TITLE
Campaign. Tried to load game. Received error. Can only load crash save.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrsmithdemos/open-ig#902]
```
   Java version: 1.7.0_21
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows XP, x86, 5.1
   Game version: 0.95.200
   Command line: [-memonce, -en]
   Available memory: 295 MB
   Maximum memory: 804 MB
   Parallelism: 2
   Language: en
   Date and time: 2014-11-07T22:46:43.750Z
----
A crash save may have been created. Please attach it in the issue report 
(zipped).
C:\Program Files\Imperium\save\default\save-2014-11-07-22-46-43-765.xml.gz
java.lang.AssertionError: DiplomaticRelation.first unknown: <relation 
first='Pirates2' second='Pirates' full='true' trade-agreement='false' 
strong-alliance='false' wont-talk='true' 
last-contact='3427-08-18T01:50:00.000Z' value='29.0' ally-against=''/>

    at hu.openig.model.World.loadDiplomaticRelations(World.java:2893)
    at hu.openig.model.World.loadState(World.java:1542)
    at hu.openig.GameWindow.loadWorldData(GameWindow.java:2322)
    at hu.openig.GameWindow$13.run(GameWindow.java:1557)
    at java.lang.Thread.run(Unknown Source)
```

Original issue reported on code.google.com by `Jonathan...@gmail.com` on 7 Nov 2014 at 10:51

Attachments:
- [save-2014-11-07-22-37-46-703.xml.gz](https://storage.googleapis.com/google-code-attachments/open-ig/issue-902/comment-0/save-2014-11-07-22-37-46-703.xml.gz)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. Will post a new version shortly.
```

Original comment by `akarn...@gmail.com` on 7 Nov 2014 at 11:16
- Changed state: **Fixed**
